// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: playback/playback_req_res.proto
// Protobuf Java Version: 4.30.2

package com.movieplatform.proto.playback;

/**
 * <pre>
 * Get playback analytics request
 * </pre>
 *
 * Protobuf type {@code proto.playback.GetPlaybackAnalyticsRequest}
 */
public final class GetPlaybackAnalyticsRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:proto.playback.GetPlaybackAnalyticsRequest)
    GetPlaybackAnalyticsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      GetPlaybackAnalyticsRequest.class.getName());
  }
  // Use GetPlaybackAnalyticsRequest.newBuilder() to construct.
  private GetPlaybackAnalyticsRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetPlaybackAnalyticsRequest() {
    userId_ = "";
    contentId_ = "";
    metricTypes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.movieplatform.proto.playback.PlaybackReqResProto.internal_static_proto_playback_GetPlaybackAnalyticsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.movieplatform.proto.playback.PlaybackReqResProto.internal_static_proto_playback_GetPlaybackAnalyticsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest.class, com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest.Builder.class);
  }

  private int bitField0_;
  public static final int BASE_REQUEST_FIELD_NUMBER = 1;
  private com.movieplatform.proto.common.BaseRequest baseRequest_;
  /**
   * <code>.proto.common.BaseRequest base_request = 1;</code>
   * @return Whether the baseRequest field is set.
   */
  @java.lang.Override
  public boolean hasBaseRequest() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.proto.common.BaseRequest base_request = 1;</code>
   * @return The baseRequest.
   */
  @java.lang.Override
  public com.movieplatform.proto.common.BaseRequest getBaseRequest() {
    return baseRequest_ == null ? com.movieplatform.proto.common.BaseRequest.getDefaultInstance() : baseRequest_;
  }
  /**
   * <code>.proto.common.BaseRequest base_request = 1;</code>
   */
  @java.lang.Override
  public com.movieplatform.proto.common.BaseRequestOrBuilder getBaseRequestOrBuilder() {
    return baseRequest_ == null ? com.movieplatform.proto.common.BaseRequest.getDefaultInstance() : baseRequest_;
  }

  public static final int USER_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object userId_ = "";
  /**
   * <pre>
   * User ID (optional)
   * </pre>
   *
   * <code>string user_id = 2;</code>
   * @return The userId.
   */
  @java.lang.Override
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * User ID (optional)
   * </pre>
   *
   * <code>string user_id = 2;</code>
   * @return The bytes for userId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTENT_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object contentId_ = "";
  /**
   * <pre>
   * Content ID (optional)
   * </pre>
   *
   * <code>string content_id = 3;</code>
   * @return The contentId.
   */
  @java.lang.Override
  public java.lang.String getContentId() {
    java.lang.Object ref = contentId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contentId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Content ID (optional)
   * </pre>
   *
   * <code>string content_id = 3;</code>
   * @return The bytes for contentId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContentIdBytes() {
    java.lang.Object ref = contentId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contentId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int START_DATE_FIELD_NUMBER = 4;
  private com.movieplatform.proto.common.DateTime startDate_;
  /**
   * <pre>
   * Start date
   * </pre>
   *
   * <code>.proto.common.DateTime start_date = 4;</code>
   * @return Whether the startDate field is set.
   */
  @java.lang.Override
  public boolean hasStartDate() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Start date
   * </pre>
   *
   * <code>.proto.common.DateTime start_date = 4;</code>
   * @return The startDate.
   */
  @java.lang.Override
  public com.movieplatform.proto.common.DateTime getStartDate() {
    return startDate_ == null ? com.movieplatform.proto.common.DateTime.getDefaultInstance() : startDate_;
  }
  /**
   * <pre>
   * Start date
   * </pre>
   *
   * <code>.proto.common.DateTime start_date = 4;</code>
   */
  @java.lang.Override
  public com.movieplatform.proto.common.DateTimeOrBuilder getStartDateOrBuilder() {
    return startDate_ == null ? com.movieplatform.proto.common.DateTime.getDefaultInstance() : startDate_;
  }

  public static final int END_DATE_FIELD_NUMBER = 5;
  private com.movieplatform.proto.common.DateTime endDate_;
  /**
   * <pre>
   * End date
   * </pre>
   *
   * <code>.proto.common.DateTime end_date = 5;</code>
   * @return Whether the endDate field is set.
   */
  @java.lang.Override
  public boolean hasEndDate() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * End date
   * </pre>
   *
   * <code>.proto.common.DateTime end_date = 5;</code>
   * @return The endDate.
   */
  @java.lang.Override
  public com.movieplatform.proto.common.DateTime getEndDate() {
    return endDate_ == null ? com.movieplatform.proto.common.DateTime.getDefaultInstance() : endDate_;
  }
  /**
   * <pre>
   * End date
   * </pre>
   *
   * <code>.proto.common.DateTime end_date = 5;</code>
   */
  @java.lang.Override
  public com.movieplatform.proto.common.DateTimeOrBuilder getEndDateOrBuilder() {
    return endDate_ == null ? com.movieplatform.proto.common.DateTime.getDefaultInstance() : endDate_;
  }

  public static final int METRIC_TYPES_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList metricTypes_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * Types of metrics
   * </pre>
   *
   * <code>repeated string metric_types = 6;</code>
   * @return A list containing the metricTypes.
   */
  public com.google.protobuf.ProtocolStringList
      getMetricTypesList() {
    return metricTypes_;
  }
  /**
   * <pre>
   * Types of metrics
   * </pre>
   *
   * <code>repeated string metric_types = 6;</code>
   * @return The count of metricTypes.
   */
  public int getMetricTypesCount() {
    return metricTypes_.size();
  }
  /**
   * <pre>
   * Types of metrics
   * </pre>
   *
   * <code>repeated string metric_types = 6;</code>
   * @param index The index of the element to return.
   * @return The metricTypes at the given index.
   */
  public java.lang.String getMetricTypes(int index) {
    return metricTypes_.get(index);
  }
  /**
   * <pre>
   * Types of metrics
   * </pre>
   *
   * <code>repeated string metric_types = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the metricTypes at the given index.
   */
  public com.google.protobuf.ByteString
      getMetricTypesBytes(int index) {
    return metricTypes_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getBaseRequest());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, userId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(contentId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, contentId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(4, getStartDate());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(5, getEndDate());
    }
    for (int i = 0; i < metricTypes_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, metricTypes_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBaseRequest());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, userId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(contentId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, contentId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getStartDate());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getEndDate());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < metricTypes_.size(); i++) {
        dataSize += computeStringSizeNoTag(metricTypes_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getMetricTypesList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest)) {
      return super.equals(obj);
    }
    com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest other = (com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest) obj;

    if (hasBaseRequest() != other.hasBaseRequest()) return false;
    if (hasBaseRequest()) {
      if (!getBaseRequest()
          .equals(other.getBaseRequest())) return false;
    }
    if (!getUserId()
        .equals(other.getUserId())) return false;
    if (!getContentId()
        .equals(other.getContentId())) return false;
    if (hasStartDate() != other.hasStartDate()) return false;
    if (hasStartDate()) {
      if (!getStartDate()
          .equals(other.getStartDate())) return false;
    }
    if (hasEndDate() != other.hasEndDate()) return false;
    if (hasEndDate()) {
      if (!getEndDate()
          .equals(other.getEndDate())) return false;
    }
    if (!getMetricTypesList()
        .equals(other.getMetricTypesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBaseRequest()) {
      hash = (37 * hash) + BASE_REQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getBaseRequest().hashCode();
    }
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId().hashCode();
    hash = (37 * hash) + CONTENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getContentId().hashCode();
    if (hasStartDate()) {
      hash = (37 * hash) + START_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getStartDate().hashCode();
    }
    if (hasEndDate()) {
      hash = (37 * hash) + END_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getEndDate().hashCode();
    }
    if (getMetricTypesCount() > 0) {
      hash = (37 * hash) + METRIC_TYPES_FIELD_NUMBER;
      hash = (53 * hash) + getMetricTypesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Get playback analytics request
   * </pre>
   *
   * Protobuf type {@code proto.playback.GetPlaybackAnalyticsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.playback.GetPlaybackAnalyticsRequest)
      com.movieplatform.proto.playback.GetPlaybackAnalyticsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.movieplatform.proto.playback.PlaybackReqResProto.internal_static_proto_playback_GetPlaybackAnalyticsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.movieplatform.proto.playback.PlaybackReqResProto.internal_static_proto_playback_GetPlaybackAnalyticsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest.class, com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest.Builder.class);
    }

    // Construct using com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetBaseRequestFieldBuilder();
        internalGetStartDateFieldBuilder();
        internalGetEndDateFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      baseRequest_ = null;
      if (baseRequestBuilder_ != null) {
        baseRequestBuilder_.dispose();
        baseRequestBuilder_ = null;
      }
      userId_ = "";
      contentId_ = "";
      startDate_ = null;
      if (startDateBuilder_ != null) {
        startDateBuilder_.dispose();
        startDateBuilder_ = null;
      }
      endDate_ = null;
      if (endDateBuilder_ != null) {
        endDateBuilder_.dispose();
        endDateBuilder_ = null;
      }
      metricTypes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.movieplatform.proto.playback.PlaybackReqResProto.internal_static_proto_playback_GetPlaybackAnalyticsRequest_descriptor;
    }

    @java.lang.Override
    public com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest getDefaultInstanceForType() {
      return com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest build() {
      com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest buildPartial() {
      com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest result = new com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.baseRequest_ = baseRequestBuilder_ == null
            ? baseRequest_
            : baseRequestBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.userId_ = userId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.contentId_ = contentId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.startDate_ = startDateBuilder_ == null
            ? startDate_
            : startDateBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.endDate_ = endDateBuilder_ == null
            ? endDate_
            : endDateBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        metricTypes_.makeImmutable();
        result.metricTypes_ = metricTypes_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest) {
        return mergeFrom((com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest other) {
      if (other == com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest.getDefaultInstance()) return this;
      if (other.hasBaseRequest()) {
        mergeBaseRequest(other.getBaseRequest());
      }
      if (!other.getUserId().isEmpty()) {
        userId_ = other.userId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getContentId().isEmpty()) {
        contentId_ = other.contentId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasStartDate()) {
        mergeStartDate(other.getStartDate());
      }
      if (other.hasEndDate()) {
        mergeEndDate(other.getEndDate());
      }
      if (!other.metricTypes_.isEmpty()) {
        if (metricTypes_.isEmpty()) {
          metricTypes_ = other.metricTypes_;
          bitField0_ |= 0x00000020;
        } else {
          ensureMetricTypesIsMutable();
          metricTypes_.addAll(other.metricTypes_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetBaseRequestFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              userId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              contentId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetStartDateFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  internalGetEndDateFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureMetricTypesIsMutable();
              metricTypes_.add(s);
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.movieplatform.proto.common.BaseRequest baseRequest_;
    private com.google.protobuf.SingleFieldBuilder<
        com.movieplatform.proto.common.BaseRequest, com.movieplatform.proto.common.BaseRequest.Builder, com.movieplatform.proto.common.BaseRequestOrBuilder> baseRequestBuilder_;
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     * @return Whether the baseRequest field is set.
     */
    public boolean hasBaseRequest() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     * @return The baseRequest.
     */
    public com.movieplatform.proto.common.BaseRequest getBaseRequest() {
      if (baseRequestBuilder_ == null) {
        return baseRequest_ == null ? com.movieplatform.proto.common.BaseRequest.getDefaultInstance() : baseRequest_;
      } else {
        return baseRequestBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     */
    public Builder setBaseRequest(com.movieplatform.proto.common.BaseRequest value) {
      if (baseRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        baseRequest_ = value;
      } else {
        baseRequestBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     */
    public Builder setBaseRequest(
        com.movieplatform.proto.common.BaseRequest.Builder builderForValue) {
      if (baseRequestBuilder_ == null) {
        baseRequest_ = builderForValue.build();
      } else {
        baseRequestBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     */
    public Builder mergeBaseRequest(com.movieplatform.proto.common.BaseRequest value) {
      if (baseRequestBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          baseRequest_ != null &&
          baseRequest_ != com.movieplatform.proto.common.BaseRequest.getDefaultInstance()) {
          getBaseRequestBuilder().mergeFrom(value);
        } else {
          baseRequest_ = value;
        }
      } else {
        baseRequestBuilder_.mergeFrom(value);
      }
      if (baseRequest_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     */
    public Builder clearBaseRequest() {
      bitField0_ = (bitField0_ & ~0x00000001);
      baseRequest_ = null;
      if (baseRequestBuilder_ != null) {
        baseRequestBuilder_.dispose();
        baseRequestBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     */
    public com.movieplatform.proto.common.BaseRequest.Builder getBaseRequestBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetBaseRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     */
    public com.movieplatform.proto.common.BaseRequestOrBuilder getBaseRequestOrBuilder() {
      if (baseRequestBuilder_ != null) {
        return baseRequestBuilder_.getMessageOrBuilder();
      } else {
        return baseRequest_ == null ?
            com.movieplatform.proto.common.BaseRequest.getDefaultInstance() : baseRequest_;
      }
    }
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.movieplatform.proto.common.BaseRequest, com.movieplatform.proto.common.BaseRequest.Builder, com.movieplatform.proto.common.BaseRequestOrBuilder> 
        internalGetBaseRequestFieldBuilder() {
      if (baseRequestBuilder_ == null) {
        baseRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.movieplatform.proto.common.BaseRequest, com.movieplatform.proto.common.BaseRequest.Builder, com.movieplatform.proto.common.BaseRequestOrBuilder>(
                getBaseRequest(),
                getParentForChildren(),
                isClean());
        baseRequest_ = null;
      }
      return baseRequestBuilder_;
    }

    private java.lang.Object userId_ = "";
    /**
     * <pre>
     * User ID (optional)
     * </pre>
     *
     * <code>string user_id = 2;</code>
     * @return The userId.
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * User ID (optional)
     * </pre>
     *
     * <code>string user_id = 2;</code>
     * @return The bytes for userId.
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * User ID (optional)
     * </pre>
     *
     * <code>string user_id = 2;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      userId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * User ID (optional)
     * </pre>
     *
     * <code>string user_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      userId_ = getDefaultInstance().getUserId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * User ID (optional)
     * </pre>
     *
     * <code>string user_id = 2;</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      userId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object contentId_ = "";
    /**
     * <pre>
     * Content ID (optional)
     * </pre>
     *
     * <code>string content_id = 3;</code>
     * @return The contentId.
     */
    public java.lang.String getContentId() {
      java.lang.Object ref = contentId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contentId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Content ID (optional)
     * </pre>
     *
     * <code>string content_id = 3;</code>
     * @return The bytes for contentId.
     */
    public com.google.protobuf.ByteString
        getContentIdBytes() {
      java.lang.Object ref = contentId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Content ID (optional)
     * </pre>
     *
     * <code>string content_id = 3;</code>
     * @param value The contentId to set.
     * @return This builder for chaining.
     */
    public Builder setContentId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      contentId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Content ID (optional)
     * </pre>
     *
     * <code>string content_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearContentId() {
      contentId_ = getDefaultInstance().getContentId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Content ID (optional)
     * </pre>
     *
     * <code>string content_id = 3;</code>
     * @param value The bytes for contentId to set.
     * @return This builder for chaining.
     */
    public Builder setContentIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      contentId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private com.movieplatform.proto.common.DateTime startDate_;
    private com.google.protobuf.SingleFieldBuilder<
        com.movieplatform.proto.common.DateTime, com.movieplatform.proto.common.DateTime.Builder, com.movieplatform.proto.common.DateTimeOrBuilder> startDateBuilder_;
    /**
     * <pre>
     * Start date
     * </pre>
     *
     * <code>.proto.common.DateTime start_date = 4;</code>
     * @return Whether the startDate field is set.
     */
    public boolean hasStartDate() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Start date
     * </pre>
     *
     * <code>.proto.common.DateTime start_date = 4;</code>
     * @return The startDate.
     */
    public com.movieplatform.proto.common.DateTime getStartDate() {
      if (startDateBuilder_ == null) {
        return startDate_ == null ? com.movieplatform.proto.common.DateTime.getDefaultInstance() : startDate_;
      } else {
        return startDateBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Start date
     * </pre>
     *
     * <code>.proto.common.DateTime start_date = 4;</code>
     */
    public Builder setStartDate(com.movieplatform.proto.common.DateTime value) {
      if (startDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        startDate_ = value;
      } else {
        startDateBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Start date
     * </pre>
     *
     * <code>.proto.common.DateTime start_date = 4;</code>
     */
    public Builder setStartDate(
        com.movieplatform.proto.common.DateTime.Builder builderForValue) {
      if (startDateBuilder_ == null) {
        startDate_ = builderForValue.build();
      } else {
        startDateBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Start date
     * </pre>
     *
     * <code>.proto.common.DateTime start_date = 4;</code>
     */
    public Builder mergeStartDate(com.movieplatform.proto.common.DateTime value) {
      if (startDateBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          startDate_ != null &&
          startDate_ != com.movieplatform.proto.common.DateTime.getDefaultInstance()) {
          getStartDateBuilder().mergeFrom(value);
        } else {
          startDate_ = value;
        }
      } else {
        startDateBuilder_.mergeFrom(value);
      }
      if (startDate_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Start date
     * </pre>
     *
     * <code>.proto.common.DateTime start_date = 4;</code>
     */
    public Builder clearStartDate() {
      bitField0_ = (bitField0_ & ~0x00000008);
      startDate_ = null;
      if (startDateBuilder_ != null) {
        startDateBuilder_.dispose();
        startDateBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Start date
     * </pre>
     *
     * <code>.proto.common.DateTime start_date = 4;</code>
     */
    public com.movieplatform.proto.common.DateTime.Builder getStartDateBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return internalGetStartDateFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Start date
     * </pre>
     *
     * <code>.proto.common.DateTime start_date = 4;</code>
     */
    public com.movieplatform.proto.common.DateTimeOrBuilder getStartDateOrBuilder() {
      if (startDateBuilder_ != null) {
        return startDateBuilder_.getMessageOrBuilder();
      } else {
        return startDate_ == null ?
            com.movieplatform.proto.common.DateTime.getDefaultInstance() : startDate_;
      }
    }
    /**
     * <pre>
     * Start date
     * </pre>
     *
     * <code>.proto.common.DateTime start_date = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.movieplatform.proto.common.DateTime, com.movieplatform.proto.common.DateTime.Builder, com.movieplatform.proto.common.DateTimeOrBuilder> 
        internalGetStartDateFieldBuilder() {
      if (startDateBuilder_ == null) {
        startDateBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.movieplatform.proto.common.DateTime, com.movieplatform.proto.common.DateTime.Builder, com.movieplatform.proto.common.DateTimeOrBuilder>(
                getStartDate(),
                getParentForChildren(),
                isClean());
        startDate_ = null;
      }
      return startDateBuilder_;
    }

    private com.movieplatform.proto.common.DateTime endDate_;
    private com.google.protobuf.SingleFieldBuilder<
        com.movieplatform.proto.common.DateTime, com.movieplatform.proto.common.DateTime.Builder, com.movieplatform.proto.common.DateTimeOrBuilder> endDateBuilder_;
    /**
     * <pre>
     * End date
     * </pre>
     *
     * <code>.proto.common.DateTime end_date = 5;</code>
     * @return Whether the endDate field is set.
     */
    public boolean hasEndDate() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * End date
     * </pre>
     *
     * <code>.proto.common.DateTime end_date = 5;</code>
     * @return The endDate.
     */
    public com.movieplatform.proto.common.DateTime getEndDate() {
      if (endDateBuilder_ == null) {
        return endDate_ == null ? com.movieplatform.proto.common.DateTime.getDefaultInstance() : endDate_;
      } else {
        return endDateBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * End date
     * </pre>
     *
     * <code>.proto.common.DateTime end_date = 5;</code>
     */
    public Builder setEndDate(com.movieplatform.proto.common.DateTime value) {
      if (endDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        endDate_ = value;
      } else {
        endDateBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * End date
     * </pre>
     *
     * <code>.proto.common.DateTime end_date = 5;</code>
     */
    public Builder setEndDate(
        com.movieplatform.proto.common.DateTime.Builder builderForValue) {
      if (endDateBuilder_ == null) {
        endDate_ = builderForValue.build();
      } else {
        endDateBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * End date
     * </pre>
     *
     * <code>.proto.common.DateTime end_date = 5;</code>
     */
    public Builder mergeEndDate(com.movieplatform.proto.common.DateTime value) {
      if (endDateBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          endDate_ != null &&
          endDate_ != com.movieplatform.proto.common.DateTime.getDefaultInstance()) {
          getEndDateBuilder().mergeFrom(value);
        } else {
          endDate_ = value;
        }
      } else {
        endDateBuilder_.mergeFrom(value);
      }
      if (endDate_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * End date
     * </pre>
     *
     * <code>.proto.common.DateTime end_date = 5;</code>
     */
    public Builder clearEndDate() {
      bitField0_ = (bitField0_ & ~0x00000010);
      endDate_ = null;
      if (endDateBuilder_ != null) {
        endDateBuilder_.dispose();
        endDateBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * End date
     * </pre>
     *
     * <code>.proto.common.DateTime end_date = 5;</code>
     */
    public com.movieplatform.proto.common.DateTime.Builder getEndDateBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return internalGetEndDateFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * End date
     * </pre>
     *
     * <code>.proto.common.DateTime end_date = 5;</code>
     */
    public com.movieplatform.proto.common.DateTimeOrBuilder getEndDateOrBuilder() {
      if (endDateBuilder_ != null) {
        return endDateBuilder_.getMessageOrBuilder();
      } else {
        return endDate_ == null ?
            com.movieplatform.proto.common.DateTime.getDefaultInstance() : endDate_;
      }
    }
    /**
     * <pre>
     * End date
     * </pre>
     *
     * <code>.proto.common.DateTime end_date = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.movieplatform.proto.common.DateTime, com.movieplatform.proto.common.DateTime.Builder, com.movieplatform.proto.common.DateTimeOrBuilder> 
        internalGetEndDateFieldBuilder() {
      if (endDateBuilder_ == null) {
        endDateBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.movieplatform.proto.common.DateTime, com.movieplatform.proto.common.DateTime.Builder, com.movieplatform.proto.common.DateTimeOrBuilder>(
                getEndDate(),
                getParentForChildren(),
                isClean());
        endDate_ = null;
      }
      return endDateBuilder_;
    }

    private com.google.protobuf.LazyStringArrayList metricTypes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureMetricTypesIsMutable() {
      if (!metricTypes_.isModifiable()) {
        metricTypes_ = new com.google.protobuf.LazyStringArrayList(metricTypes_);
      }
      bitField0_ |= 0x00000020;
    }
    /**
     * <pre>
     * Types of metrics
     * </pre>
     *
     * <code>repeated string metric_types = 6;</code>
     * @return A list containing the metricTypes.
     */
    public com.google.protobuf.ProtocolStringList
        getMetricTypesList() {
      metricTypes_.makeImmutable();
      return metricTypes_;
    }
    /**
     * <pre>
     * Types of metrics
     * </pre>
     *
     * <code>repeated string metric_types = 6;</code>
     * @return The count of metricTypes.
     */
    public int getMetricTypesCount() {
      return metricTypes_.size();
    }
    /**
     * <pre>
     * Types of metrics
     * </pre>
     *
     * <code>repeated string metric_types = 6;</code>
     * @param index The index of the element to return.
     * @return The metricTypes at the given index.
     */
    public java.lang.String getMetricTypes(int index) {
      return metricTypes_.get(index);
    }
    /**
     * <pre>
     * Types of metrics
     * </pre>
     *
     * <code>repeated string metric_types = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the metricTypes at the given index.
     */
    public com.google.protobuf.ByteString
        getMetricTypesBytes(int index) {
      return metricTypes_.getByteString(index);
    }
    /**
     * <pre>
     * Types of metrics
     * </pre>
     *
     * <code>repeated string metric_types = 6;</code>
     * @param index The index to set the value at.
     * @param value The metricTypes to set.
     * @return This builder for chaining.
     */
    public Builder setMetricTypes(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureMetricTypesIsMutable();
      metricTypes_.set(index, value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Types of metrics
     * </pre>
     *
     * <code>repeated string metric_types = 6;</code>
     * @param value The metricTypes to add.
     * @return This builder for chaining.
     */
    public Builder addMetricTypes(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureMetricTypesIsMutable();
      metricTypes_.add(value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Types of metrics
     * </pre>
     *
     * <code>repeated string metric_types = 6;</code>
     * @param values The metricTypes to add.
     * @return This builder for chaining.
     */
    public Builder addAllMetricTypes(
        java.lang.Iterable<java.lang.String> values) {
      ensureMetricTypesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, metricTypes_);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Types of metrics
     * </pre>
     *
     * <code>repeated string metric_types = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMetricTypes() {
      metricTypes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000020);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Types of metrics
     * </pre>
     *
     * <code>repeated string metric_types = 6;</code>
     * @param value The bytes of the metricTypes to add.
     * @return This builder for chaining.
     */
    public Builder addMetricTypesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureMetricTypesIsMutable();
      metricTypes_.add(value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:proto.playback.GetPlaybackAnalyticsRequest)
  }

  // @@protoc_insertion_point(class_scope:proto.playback.GetPlaybackAnalyticsRequest)
  private static final com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest();
  }

  public static com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetPlaybackAnalyticsRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetPlaybackAnalyticsRequest>() {
    @java.lang.Override
    public GetPlaybackAnalyticsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetPlaybackAnalyticsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetPlaybackAnalyticsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.movieplatform.proto.playback.GetPlaybackAnalyticsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

