// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: playback/playback_req_res.proto
// Protobuf Java Version: 4.29.3

package com.movieplatform.proto.playback;

public interface GetPlaybackSessionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.playback.GetPlaybackSessionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto.common.BaseRequest base_request = 1;</code>
   * @return Whether the baseRequest field is set.
   */
  boolean hasBaseRequest();
  /**
   * <code>.proto.common.BaseRequest base_request = 1;</code>
   * @return The baseRequest.
   */
  com.movieplatform.proto.common.BaseRequest getBaseRequest();
  /**
   * <code>.proto.common.BaseRequest base_request = 1;</code>
   */
  com.movieplatform.proto.common.BaseRequestOrBuilder getBaseRequestOrBuilder();

  /**
   * <pre>
   * Session ID to retrieve
   * </pre>
   *
   * <code>string session_id = 2;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <pre>
   * Session ID to retrieve
   * </pre>
   *
   * <code>string session_id = 2;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <pre>
   * Include progress information
   * </pre>
   *
   * <code>bool include_progress = 3;</code>
   * @return The includeProgress.
   */
  boolean getIncludeProgress();

  /**
   * <pre>
   * Include streaming metrics
   * </pre>
   *
   * <code>bool include_metrics = 4;</code>
   * @return The includeMetrics.
   */
  boolean getIncludeMetrics();
}
