// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: playback/playback_req_res.proto
// Protobuf Java Version: 4.30.2

package com.movieplatform.proto.playback;

public interface GetStreamingMetricsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.playback.GetStreamingMetricsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   * @return Whether the baseResponse field is set.
   */
  boolean hasBaseResponse();
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   * @return The baseResponse.
   */
  com.movieplatform.proto.common.BaseResponse getBaseResponse();
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   */
  com.movieplatform.proto.common.BaseResponseOrBuilder getBaseResponseOrBuilder();

  /**
   * <pre>
   * Streaming metrics
   * </pre>
   *
   * <code>.proto.playback.StreamingMetrics metrics = 2;</code>
   * @return Whether the metrics field is set.
   */
  boolean hasMetrics();
  /**
   * <pre>
   * Streaming metrics
   * </pre>
   *
   * <code>.proto.playback.StreamingMetrics metrics = 2;</code>
   * @return The metrics.
   */
  com.movieplatform.proto.playback.StreamingMetrics getMetrics();
  /**
   * <pre>
   * Streaming metrics
   * </pre>
   *
   * <code>.proto.playback.StreamingMetrics metrics = 2;</code>
   */
  com.movieplatform.proto.playback.StreamingMetricsOrBuilder getMetricsOrBuilder();

  /**
   * <pre>
   * Detailed metric data
   * </pre>
   *
   * <code>repeated .proto.playback.MetricDataPoint data_points = 3;</code>
   */
  java.util.List<com.movieplatform.proto.playback.MetricDataPoint> 
      getDataPointsList();
  /**
   * <pre>
   * Detailed metric data
   * </pre>
   *
   * <code>repeated .proto.playback.MetricDataPoint data_points = 3;</code>
   */
  com.movieplatform.proto.playback.MetricDataPoint getDataPoints(int index);
  /**
   * <pre>
   * Detailed metric data
   * </pre>
   *
   * <code>repeated .proto.playback.MetricDataPoint data_points = 3;</code>
   */
  int getDataPointsCount();
  /**
   * <pre>
   * Detailed metric data
   * </pre>
   *
   * <code>repeated .proto.playback.MetricDataPoint data_points = 3;</code>
   */
  java.util.List<? extends com.movieplatform.proto.playback.MetricDataPointOrBuilder> 
      getDataPointsOrBuilderList();
  /**
   * <pre>
   * Detailed metric data
   * </pre>
   *
   * <code>repeated .proto.playback.MetricDataPoint data_points = 3;</code>
   */
  com.movieplatform.proto.playback.MetricDataPointOrBuilder getDataPointsOrBuilder(
      int index);

  /**
   * <pre>
   * Format of metrics data
   * </pre>
   *
   * <code>string metrics_format = 4;</code>
   * @return The metricsFormat.
   */
  java.lang.String getMetricsFormat();
  /**
   * <pre>
   * Format of metrics data
   * </pre>
   *
   * <code>string metrics_format = 4;</code>
   * @return The bytes for metricsFormat.
   */
  com.google.protobuf.ByteString
      getMetricsFormatBytes();
}
