// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: playback/playback_req_res.proto
// Protobuf Java Version: 4.30.2

package com.movieplatform.proto.playback;

/**
 * <pre>
 * Resume playback response
 * </pre>
 *
 * Protobuf type {@code proto.playback.ResumePlaybackResponse}
 */
public final class ResumePlaybackResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:proto.playback.ResumePlaybackResponse)
    ResumePlaybackResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      ResumePlaybackResponse.class.getName());
  }
  // Use ResumePlaybackResponse.newBuilder() to construct.
  private ResumePlaybackResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ResumePlaybackResponse() {
    streamingUrl_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.movieplatform.proto.playback.PlaybackReqResProto.internal_static_proto_playback_ResumePlaybackResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.movieplatform.proto.playback.PlaybackReqResProto.internal_static_proto_playback_ResumePlaybackResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.movieplatform.proto.playback.ResumePlaybackResponse.class, com.movieplatform.proto.playback.ResumePlaybackResponse.Builder.class);
  }

  private int bitField0_;
  public static final int BASE_RESPONSE_FIELD_NUMBER = 1;
  private com.movieplatform.proto.common.BaseResponse baseResponse_;
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   * @return Whether the baseResponse field is set.
   */
  @java.lang.Override
  public boolean hasBaseResponse() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   * @return The baseResponse.
   */
  @java.lang.Override
  public com.movieplatform.proto.common.BaseResponse getBaseResponse() {
    return baseResponse_ == null ? com.movieplatform.proto.common.BaseResponse.getDefaultInstance() : baseResponse_;
  }
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   */
  @java.lang.Override
  public com.movieplatform.proto.common.BaseResponseOrBuilder getBaseResponseOrBuilder() {
    return baseResponse_ == null ? com.movieplatform.proto.common.BaseResponse.getDefaultInstance() : baseResponse_;
  }

  public static final int PLAYBACK_RESUMED_FIELD_NUMBER = 2;
  private boolean playbackResumed_ = false;
  /**
   * <pre>
   * Whether playback resumed
   * </pre>
   *
   * <code>bool playback_resumed = 2;</code>
   * @return The playbackResumed.
   */
  @java.lang.Override
  public boolean getPlaybackResumed() {
    return playbackResumed_;
  }

  public static final int STREAMING_URL_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object streamingUrl_ = "";
  /**
   * <pre>
   * Updated streaming URL
   * </pre>
   *
   * <code>string streaming_url = 3;</code>
   * @return The streamingUrl.
   */
  @java.lang.Override
  public java.lang.String getStreamingUrl() {
    java.lang.Object ref = streamingUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      streamingUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Updated streaming URL
   * </pre>
   *
   * <code>string streaming_url = 3;</code>
   * @return The bytes for streamingUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStreamingUrlBytes() {
    java.lang.Object ref = streamingUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      streamingUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESUMED_AT_FIELD_NUMBER = 4;
  private com.movieplatform.proto.common.DateTime resumedAt_;
  /**
   * <pre>
   * When playback resumed
   * </pre>
   *
   * <code>.proto.common.DateTime resumed_at = 4;</code>
   * @return Whether the resumedAt field is set.
   */
  @java.lang.Override
  public boolean hasResumedAt() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * When playback resumed
   * </pre>
   *
   * <code>.proto.common.DateTime resumed_at = 4;</code>
   * @return The resumedAt.
   */
  @java.lang.Override
  public com.movieplatform.proto.common.DateTime getResumedAt() {
    return resumedAt_ == null ? com.movieplatform.proto.common.DateTime.getDefaultInstance() : resumedAt_;
  }
  /**
   * <pre>
   * When playback resumed
   * </pre>
   *
   * <code>.proto.common.DateTime resumed_at = 4;</code>
   */
  @java.lang.Override
  public com.movieplatform.proto.common.DateTimeOrBuilder getResumedAtOrBuilder() {
    return resumedAt_ == null ? com.movieplatform.proto.common.DateTime.getDefaultInstance() : resumedAt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getBaseResponse());
    }
    if (playbackResumed_ != false) {
      output.writeBool(2, playbackResumed_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(streamingUrl_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, streamingUrl_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(4, getResumedAt());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBaseResponse());
    }
    if (playbackResumed_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, playbackResumed_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(streamingUrl_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, streamingUrl_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getResumedAt());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.movieplatform.proto.playback.ResumePlaybackResponse)) {
      return super.equals(obj);
    }
    com.movieplatform.proto.playback.ResumePlaybackResponse other = (com.movieplatform.proto.playback.ResumePlaybackResponse) obj;

    if (hasBaseResponse() != other.hasBaseResponse()) return false;
    if (hasBaseResponse()) {
      if (!getBaseResponse()
          .equals(other.getBaseResponse())) return false;
    }
    if (getPlaybackResumed()
        != other.getPlaybackResumed()) return false;
    if (!getStreamingUrl()
        .equals(other.getStreamingUrl())) return false;
    if (hasResumedAt() != other.hasResumedAt()) return false;
    if (hasResumedAt()) {
      if (!getResumedAt()
          .equals(other.getResumedAt())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBaseResponse()) {
      hash = (37 * hash) + BASE_RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getBaseResponse().hashCode();
    }
    hash = (37 * hash) + PLAYBACK_RESUMED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getPlaybackResumed());
    hash = (37 * hash) + STREAMING_URL_FIELD_NUMBER;
    hash = (53 * hash) + getStreamingUrl().hashCode();
    if (hasResumedAt()) {
      hash = (37 * hash) + RESUMED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getResumedAt().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.movieplatform.proto.playback.ResumePlaybackResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.playback.ResumePlaybackResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.playback.ResumePlaybackResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.playback.ResumePlaybackResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.playback.ResumePlaybackResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.playback.ResumePlaybackResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.playback.ResumePlaybackResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.playback.ResumePlaybackResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.movieplatform.proto.playback.ResumePlaybackResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.movieplatform.proto.playback.ResumePlaybackResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.movieplatform.proto.playback.ResumePlaybackResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.playback.ResumePlaybackResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.movieplatform.proto.playback.ResumePlaybackResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Resume playback response
   * </pre>
   *
   * Protobuf type {@code proto.playback.ResumePlaybackResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.playback.ResumePlaybackResponse)
      com.movieplatform.proto.playback.ResumePlaybackResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.movieplatform.proto.playback.PlaybackReqResProto.internal_static_proto_playback_ResumePlaybackResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.movieplatform.proto.playback.PlaybackReqResProto.internal_static_proto_playback_ResumePlaybackResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.movieplatform.proto.playback.ResumePlaybackResponse.class, com.movieplatform.proto.playback.ResumePlaybackResponse.Builder.class);
    }

    // Construct using com.movieplatform.proto.playback.ResumePlaybackResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetBaseResponseFieldBuilder();
        internalGetResumedAtFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      baseResponse_ = null;
      if (baseResponseBuilder_ != null) {
        baseResponseBuilder_.dispose();
        baseResponseBuilder_ = null;
      }
      playbackResumed_ = false;
      streamingUrl_ = "";
      resumedAt_ = null;
      if (resumedAtBuilder_ != null) {
        resumedAtBuilder_.dispose();
        resumedAtBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.movieplatform.proto.playback.PlaybackReqResProto.internal_static_proto_playback_ResumePlaybackResponse_descriptor;
    }

    @java.lang.Override
    public com.movieplatform.proto.playback.ResumePlaybackResponse getDefaultInstanceForType() {
      return com.movieplatform.proto.playback.ResumePlaybackResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.movieplatform.proto.playback.ResumePlaybackResponse build() {
      com.movieplatform.proto.playback.ResumePlaybackResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.movieplatform.proto.playback.ResumePlaybackResponse buildPartial() {
      com.movieplatform.proto.playback.ResumePlaybackResponse result = new com.movieplatform.proto.playback.ResumePlaybackResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.movieplatform.proto.playback.ResumePlaybackResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.baseResponse_ = baseResponseBuilder_ == null
            ? baseResponse_
            : baseResponseBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.playbackResumed_ = playbackResumed_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.streamingUrl_ = streamingUrl_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.resumedAt_ = resumedAtBuilder_ == null
            ? resumedAt_
            : resumedAtBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.movieplatform.proto.playback.ResumePlaybackResponse) {
        return mergeFrom((com.movieplatform.proto.playback.ResumePlaybackResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.movieplatform.proto.playback.ResumePlaybackResponse other) {
      if (other == com.movieplatform.proto.playback.ResumePlaybackResponse.getDefaultInstance()) return this;
      if (other.hasBaseResponse()) {
        mergeBaseResponse(other.getBaseResponse());
      }
      if (other.getPlaybackResumed() != false) {
        setPlaybackResumed(other.getPlaybackResumed());
      }
      if (!other.getStreamingUrl().isEmpty()) {
        streamingUrl_ = other.streamingUrl_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasResumedAt()) {
        mergeResumedAt(other.getResumedAt());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetBaseResponseFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              playbackResumed_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              streamingUrl_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetResumedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.movieplatform.proto.common.BaseResponse baseResponse_;
    private com.google.protobuf.SingleFieldBuilder<
        com.movieplatform.proto.common.BaseResponse, com.movieplatform.proto.common.BaseResponse.Builder, com.movieplatform.proto.common.BaseResponseOrBuilder> baseResponseBuilder_;
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     * @return Whether the baseResponse field is set.
     */
    public boolean hasBaseResponse() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     * @return The baseResponse.
     */
    public com.movieplatform.proto.common.BaseResponse getBaseResponse() {
      if (baseResponseBuilder_ == null) {
        return baseResponse_ == null ? com.movieplatform.proto.common.BaseResponse.getDefaultInstance() : baseResponse_;
      } else {
        return baseResponseBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public Builder setBaseResponse(com.movieplatform.proto.common.BaseResponse value) {
      if (baseResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        baseResponse_ = value;
      } else {
        baseResponseBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public Builder setBaseResponse(
        com.movieplatform.proto.common.BaseResponse.Builder builderForValue) {
      if (baseResponseBuilder_ == null) {
        baseResponse_ = builderForValue.build();
      } else {
        baseResponseBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public Builder mergeBaseResponse(com.movieplatform.proto.common.BaseResponse value) {
      if (baseResponseBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          baseResponse_ != null &&
          baseResponse_ != com.movieplatform.proto.common.BaseResponse.getDefaultInstance()) {
          getBaseResponseBuilder().mergeFrom(value);
        } else {
          baseResponse_ = value;
        }
      } else {
        baseResponseBuilder_.mergeFrom(value);
      }
      if (baseResponse_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public Builder clearBaseResponse() {
      bitField0_ = (bitField0_ & ~0x00000001);
      baseResponse_ = null;
      if (baseResponseBuilder_ != null) {
        baseResponseBuilder_.dispose();
        baseResponseBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public com.movieplatform.proto.common.BaseResponse.Builder getBaseResponseBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetBaseResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public com.movieplatform.proto.common.BaseResponseOrBuilder getBaseResponseOrBuilder() {
      if (baseResponseBuilder_ != null) {
        return baseResponseBuilder_.getMessageOrBuilder();
      } else {
        return baseResponse_ == null ?
            com.movieplatform.proto.common.BaseResponse.getDefaultInstance() : baseResponse_;
      }
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.movieplatform.proto.common.BaseResponse, com.movieplatform.proto.common.BaseResponse.Builder, com.movieplatform.proto.common.BaseResponseOrBuilder> 
        internalGetBaseResponseFieldBuilder() {
      if (baseResponseBuilder_ == null) {
        baseResponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.movieplatform.proto.common.BaseResponse, com.movieplatform.proto.common.BaseResponse.Builder, com.movieplatform.proto.common.BaseResponseOrBuilder>(
                getBaseResponse(),
                getParentForChildren(),
                isClean());
        baseResponse_ = null;
      }
      return baseResponseBuilder_;
    }

    private boolean playbackResumed_ ;
    /**
     * <pre>
     * Whether playback resumed
     * </pre>
     *
     * <code>bool playback_resumed = 2;</code>
     * @return The playbackResumed.
     */
    @java.lang.Override
    public boolean getPlaybackResumed() {
      return playbackResumed_;
    }
    /**
     * <pre>
     * Whether playback resumed
     * </pre>
     *
     * <code>bool playback_resumed = 2;</code>
     * @param value The playbackResumed to set.
     * @return This builder for chaining.
     */
    public Builder setPlaybackResumed(boolean value) {

      playbackResumed_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Whether playback resumed
     * </pre>
     *
     * <code>bool playback_resumed = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlaybackResumed() {
      bitField0_ = (bitField0_ & ~0x00000002);
      playbackResumed_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object streamingUrl_ = "";
    /**
     * <pre>
     * Updated streaming URL
     * </pre>
     *
     * <code>string streaming_url = 3;</code>
     * @return The streamingUrl.
     */
    public java.lang.String getStreamingUrl() {
      java.lang.Object ref = streamingUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        streamingUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Updated streaming URL
     * </pre>
     *
     * <code>string streaming_url = 3;</code>
     * @return The bytes for streamingUrl.
     */
    public com.google.protobuf.ByteString
        getStreamingUrlBytes() {
      java.lang.Object ref = streamingUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        streamingUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Updated streaming URL
     * </pre>
     *
     * <code>string streaming_url = 3;</code>
     * @param value The streamingUrl to set.
     * @return This builder for chaining.
     */
    public Builder setStreamingUrl(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      streamingUrl_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Updated streaming URL
     * </pre>
     *
     * <code>string streaming_url = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStreamingUrl() {
      streamingUrl_ = getDefaultInstance().getStreamingUrl();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Updated streaming URL
     * </pre>
     *
     * <code>string streaming_url = 3;</code>
     * @param value The bytes for streamingUrl to set.
     * @return This builder for chaining.
     */
    public Builder setStreamingUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      streamingUrl_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private com.movieplatform.proto.common.DateTime resumedAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.movieplatform.proto.common.DateTime, com.movieplatform.proto.common.DateTime.Builder, com.movieplatform.proto.common.DateTimeOrBuilder> resumedAtBuilder_;
    /**
     * <pre>
     * When playback resumed
     * </pre>
     *
     * <code>.proto.common.DateTime resumed_at = 4;</code>
     * @return Whether the resumedAt field is set.
     */
    public boolean hasResumedAt() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * When playback resumed
     * </pre>
     *
     * <code>.proto.common.DateTime resumed_at = 4;</code>
     * @return The resumedAt.
     */
    public com.movieplatform.proto.common.DateTime getResumedAt() {
      if (resumedAtBuilder_ == null) {
        return resumedAt_ == null ? com.movieplatform.proto.common.DateTime.getDefaultInstance() : resumedAt_;
      } else {
        return resumedAtBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * When playback resumed
     * </pre>
     *
     * <code>.proto.common.DateTime resumed_at = 4;</code>
     */
    public Builder setResumedAt(com.movieplatform.proto.common.DateTime value) {
      if (resumedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        resumedAt_ = value;
      } else {
        resumedAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * When playback resumed
     * </pre>
     *
     * <code>.proto.common.DateTime resumed_at = 4;</code>
     */
    public Builder setResumedAt(
        com.movieplatform.proto.common.DateTime.Builder builderForValue) {
      if (resumedAtBuilder_ == null) {
        resumedAt_ = builderForValue.build();
      } else {
        resumedAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * When playback resumed
     * </pre>
     *
     * <code>.proto.common.DateTime resumed_at = 4;</code>
     */
    public Builder mergeResumedAt(com.movieplatform.proto.common.DateTime value) {
      if (resumedAtBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          resumedAt_ != null &&
          resumedAt_ != com.movieplatform.proto.common.DateTime.getDefaultInstance()) {
          getResumedAtBuilder().mergeFrom(value);
        } else {
          resumedAt_ = value;
        }
      } else {
        resumedAtBuilder_.mergeFrom(value);
      }
      if (resumedAt_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * When playback resumed
     * </pre>
     *
     * <code>.proto.common.DateTime resumed_at = 4;</code>
     */
    public Builder clearResumedAt() {
      bitField0_ = (bitField0_ & ~0x00000008);
      resumedAt_ = null;
      if (resumedAtBuilder_ != null) {
        resumedAtBuilder_.dispose();
        resumedAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * When playback resumed
     * </pre>
     *
     * <code>.proto.common.DateTime resumed_at = 4;</code>
     */
    public com.movieplatform.proto.common.DateTime.Builder getResumedAtBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return internalGetResumedAtFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * When playback resumed
     * </pre>
     *
     * <code>.proto.common.DateTime resumed_at = 4;</code>
     */
    public com.movieplatform.proto.common.DateTimeOrBuilder getResumedAtOrBuilder() {
      if (resumedAtBuilder_ != null) {
        return resumedAtBuilder_.getMessageOrBuilder();
      } else {
        return resumedAt_ == null ?
            com.movieplatform.proto.common.DateTime.getDefaultInstance() : resumedAt_;
      }
    }
    /**
     * <pre>
     * When playback resumed
     * </pre>
     *
     * <code>.proto.common.DateTime resumed_at = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.movieplatform.proto.common.DateTime, com.movieplatform.proto.common.DateTime.Builder, com.movieplatform.proto.common.DateTimeOrBuilder> 
        internalGetResumedAtFieldBuilder() {
      if (resumedAtBuilder_ == null) {
        resumedAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.movieplatform.proto.common.DateTime, com.movieplatform.proto.common.DateTime.Builder, com.movieplatform.proto.common.DateTimeOrBuilder>(
                getResumedAt(),
                getParentForChildren(),
                isClean());
        resumedAt_ = null;
      }
      return resumedAtBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:proto.playback.ResumePlaybackResponse)
  }

  // @@protoc_insertion_point(class_scope:proto.playback.ResumePlaybackResponse)
  private static final com.movieplatform.proto.playback.ResumePlaybackResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.movieplatform.proto.playback.ResumePlaybackResponse();
  }

  public static com.movieplatform.proto.playback.ResumePlaybackResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResumePlaybackResponse>
      PARSER = new com.google.protobuf.AbstractParser<ResumePlaybackResponse>() {
    @java.lang.Override
    public ResumePlaybackResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ResumePlaybackResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResumePlaybackResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.movieplatform.proto.playback.ResumePlaybackResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

