// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: auth/auth_req_res.proto
// Protobuf Java Version: 4.30.2

package com.movieplatform.proto.auth;

public interface DisableMFARequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.auth.DisableMFARequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto.common.BaseRequest base_request = 1;</code>
   * @return Whether the baseRequest field is set.
   */
  boolean hasBaseRequest();
  /**
   * <code>.proto.common.BaseRequest base_request = 1;</code>
   * @return The baseRequest.
   */
  com.movieplatform.proto.common.BaseRequest getBaseRequest();
  /**
   * <code>.proto.common.BaseRequest base_request = 1;</code>
   */
  com.movieplatform.proto.common.BaseRequestOrBuilder getBaseRequestOrBuilder();

  /**
   * <pre>
   * Current MFA code for verification
   * </pre>
   *
   * <code>string mfa_code = 2;</code>
   * @return The mfaCode.
   */
  java.lang.String getMfaCode();
  /**
   * <pre>
   * Current MFA code for verification
   * </pre>
   *
   * <code>string mfa_code = 2;</code>
   * @return The bytes for mfaCode.
   */
  com.google.protobuf.ByteString
      getMfaCodeBytes();
}
