// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notification/notification_req_res.proto
// Protobuf Java Version: 4.29.3

package com.movieplatform.proto.notification;

public interface GetEmailStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.notification.GetEmailStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   * @return Whether the baseResponse field is set.
   */
  boolean hasBaseResponse();
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   * @return The baseResponse.
   */
  com.movieplatform.proto.common.BaseResponse getBaseResponse();
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   */
  com.movieplatform.proto.common.BaseResponseOrBuilder getBaseResponseOrBuilder();

  /**
   * <pre>
   * Email status information
   * </pre>
   *
   * <code>.proto.notification.EmailStatus email_status = 2;</code>
   * @return Whether the emailStatus field is set.
   */
  boolean hasEmailStatus();
  /**
   * <pre>
   * Email status information
   * </pre>
   *
   * <code>.proto.notification.EmailStatus email_status = 2;</code>
   * @return The emailStatus.
   */
  com.movieplatform.proto.notification.EmailStatus getEmailStatus();
  /**
   * <pre>
   * Email status information
   * </pre>
   *
   * <code>.proto.notification.EmailStatus email_status = 2;</code>
   */
  com.movieplatform.proto.notification.EmailStatusOrBuilder getEmailStatusOrBuilder();
}
