// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notification/notification_req_res.proto
// Protobuf Java Version: 4.30.2

package com.movieplatform.proto.notification;

/**
 * <pre>
 * Get notification analytics response
 * </pre>
 *
 * Protobuf type {@code proto.notification.GetNotificationAnalyticsResponse}
 */
public final class GetNotificationAnalyticsResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:proto.notification.GetNotificationAnalyticsResponse)
    GetNotificationAnalyticsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      GetNotificationAnalyticsResponse.class.getName());
  }
  // Use GetNotificationAnalyticsResponse.newBuilder() to construct.
  private GetNotificationAnalyticsResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetNotificationAnalyticsResponse() {
    metrics_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.movieplatform.proto.notification.NotificationReqResProto.internal_static_proto_notification_GetNotificationAnalyticsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.movieplatform.proto.notification.NotificationReqResProto.internal_static_proto_notification_GetNotificationAnalyticsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.movieplatform.proto.notification.GetNotificationAnalyticsResponse.class, com.movieplatform.proto.notification.GetNotificationAnalyticsResponse.Builder.class);
  }

  private int bitField0_;
  public static final int BASE_RESPONSE_FIELD_NUMBER = 1;
  private com.movieplatform.proto.common.BaseResponse baseResponse_;
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   * @return Whether the baseResponse field is set.
   */
  @java.lang.Override
  public boolean hasBaseResponse() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   * @return The baseResponse.
   */
  @java.lang.Override
  public com.movieplatform.proto.common.BaseResponse getBaseResponse() {
    return baseResponse_ == null ? com.movieplatform.proto.common.BaseResponse.getDefaultInstance() : baseResponse_;
  }
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   */
  @java.lang.Override
  public com.movieplatform.proto.common.BaseResponseOrBuilder getBaseResponseOrBuilder() {
    return baseResponse_ == null ? com.movieplatform.proto.common.BaseResponse.getDefaultInstance() : baseResponse_;
  }

  public static final int METRICS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.movieplatform.proto.notification.AnalyticsMetric> metrics_;
  /**
   * <pre>
   * Analytics metrics
   * </pre>
   *
   * <code>repeated .proto.notification.AnalyticsMetric metrics = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.movieplatform.proto.notification.AnalyticsMetric> getMetricsList() {
    return metrics_;
  }
  /**
   * <pre>
   * Analytics metrics
   * </pre>
   *
   * <code>repeated .proto.notification.AnalyticsMetric metrics = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.movieplatform.proto.notification.AnalyticsMetricOrBuilder> 
      getMetricsOrBuilderList() {
    return metrics_;
  }
  /**
   * <pre>
   * Analytics metrics
   * </pre>
   *
   * <code>repeated .proto.notification.AnalyticsMetric metrics = 2;</code>
   */
  @java.lang.Override
  public int getMetricsCount() {
    return metrics_.size();
  }
  /**
   * <pre>
   * Analytics metrics
   * </pre>
   *
   * <code>repeated .proto.notification.AnalyticsMetric metrics = 2;</code>
   */
  @java.lang.Override
  public com.movieplatform.proto.notification.AnalyticsMetric getMetrics(int index) {
    return metrics_.get(index);
  }
  /**
   * <pre>
   * Analytics metrics
   * </pre>
   *
   * <code>repeated .proto.notification.AnalyticsMetric metrics = 2;</code>
   */
  @java.lang.Override
  public com.movieplatform.proto.notification.AnalyticsMetricOrBuilder getMetricsOrBuilder(
      int index) {
    return metrics_.get(index);
  }

  public static final int INSIGHTS_FIELD_NUMBER = 3;
  private com.movieplatform.proto.notification.NotificationInsights insights_;
  /**
   * <pre>
   * Notification insights
   * </pre>
   *
   * <code>.proto.notification.NotificationInsights insights = 3;</code>
   * @return Whether the insights field is set.
   */
  @java.lang.Override
  public boolean hasInsights() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Notification insights
   * </pre>
   *
   * <code>.proto.notification.NotificationInsights insights = 3;</code>
   * @return The insights.
   */
  @java.lang.Override
  public com.movieplatform.proto.notification.NotificationInsights getInsights() {
    return insights_ == null ? com.movieplatform.proto.notification.NotificationInsights.getDefaultInstance() : insights_;
  }
  /**
   * <pre>
   * Notification insights
   * </pre>
   *
   * <code>.proto.notification.NotificationInsights insights = 3;</code>
   */
  @java.lang.Override
  public com.movieplatform.proto.notification.NotificationInsightsOrBuilder getInsightsOrBuilder() {
    return insights_ == null ? com.movieplatform.proto.notification.NotificationInsights.getDefaultInstance() : insights_;
  }

  public static final int GENERATED_AT_FIELD_NUMBER = 4;
  private com.movieplatform.proto.common.DateTime generatedAt_;
  /**
   * <pre>
   * When analytics were generated
   * </pre>
   *
   * <code>.proto.common.DateTime generated_at = 4;</code>
   * @return Whether the generatedAt field is set.
   */
  @java.lang.Override
  public boolean hasGeneratedAt() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * When analytics were generated
   * </pre>
   *
   * <code>.proto.common.DateTime generated_at = 4;</code>
   * @return The generatedAt.
   */
  @java.lang.Override
  public com.movieplatform.proto.common.DateTime getGeneratedAt() {
    return generatedAt_ == null ? com.movieplatform.proto.common.DateTime.getDefaultInstance() : generatedAt_;
  }
  /**
   * <pre>
   * When analytics were generated
   * </pre>
   *
   * <code>.proto.common.DateTime generated_at = 4;</code>
   */
  @java.lang.Override
  public com.movieplatform.proto.common.DateTimeOrBuilder getGeneratedAtOrBuilder() {
    return generatedAt_ == null ? com.movieplatform.proto.common.DateTime.getDefaultInstance() : generatedAt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getBaseResponse());
    }
    for (int i = 0; i < metrics_.size(); i++) {
      output.writeMessage(2, metrics_.get(i));
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getInsights());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(4, getGeneratedAt());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBaseResponse());
    }
    for (int i = 0; i < metrics_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, metrics_.get(i));
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getInsights());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getGeneratedAt());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.movieplatform.proto.notification.GetNotificationAnalyticsResponse)) {
      return super.equals(obj);
    }
    com.movieplatform.proto.notification.GetNotificationAnalyticsResponse other = (com.movieplatform.proto.notification.GetNotificationAnalyticsResponse) obj;

    if (hasBaseResponse() != other.hasBaseResponse()) return false;
    if (hasBaseResponse()) {
      if (!getBaseResponse()
          .equals(other.getBaseResponse())) return false;
    }
    if (!getMetricsList()
        .equals(other.getMetricsList())) return false;
    if (hasInsights() != other.hasInsights()) return false;
    if (hasInsights()) {
      if (!getInsights()
          .equals(other.getInsights())) return false;
    }
    if (hasGeneratedAt() != other.hasGeneratedAt()) return false;
    if (hasGeneratedAt()) {
      if (!getGeneratedAt()
          .equals(other.getGeneratedAt())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBaseResponse()) {
      hash = (37 * hash) + BASE_RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getBaseResponse().hashCode();
    }
    if (getMetricsCount() > 0) {
      hash = (37 * hash) + METRICS_FIELD_NUMBER;
      hash = (53 * hash) + getMetricsList().hashCode();
    }
    if (hasInsights()) {
      hash = (37 * hash) + INSIGHTS_FIELD_NUMBER;
      hash = (53 * hash) + getInsights().hashCode();
    }
    if (hasGeneratedAt()) {
      hash = (37 * hash) + GENERATED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getGeneratedAt().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.movieplatform.proto.notification.GetNotificationAnalyticsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.notification.GetNotificationAnalyticsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.notification.GetNotificationAnalyticsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.notification.GetNotificationAnalyticsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.notification.GetNotificationAnalyticsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.notification.GetNotificationAnalyticsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.notification.GetNotificationAnalyticsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.notification.GetNotificationAnalyticsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.movieplatform.proto.notification.GetNotificationAnalyticsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.movieplatform.proto.notification.GetNotificationAnalyticsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.movieplatform.proto.notification.GetNotificationAnalyticsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.notification.GetNotificationAnalyticsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.movieplatform.proto.notification.GetNotificationAnalyticsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Get notification analytics response
   * </pre>
   *
   * Protobuf type {@code proto.notification.GetNotificationAnalyticsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.notification.GetNotificationAnalyticsResponse)
      com.movieplatform.proto.notification.GetNotificationAnalyticsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.movieplatform.proto.notification.NotificationReqResProto.internal_static_proto_notification_GetNotificationAnalyticsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.movieplatform.proto.notification.NotificationReqResProto.internal_static_proto_notification_GetNotificationAnalyticsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.movieplatform.proto.notification.GetNotificationAnalyticsResponse.class, com.movieplatform.proto.notification.GetNotificationAnalyticsResponse.Builder.class);
    }

    // Construct using com.movieplatform.proto.notification.GetNotificationAnalyticsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetBaseResponseFieldBuilder();
        internalGetMetricsFieldBuilder();
        internalGetInsightsFieldBuilder();
        internalGetGeneratedAtFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      baseResponse_ = null;
      if (baseResponseBuilder_ != null) {
        baseResponseBuilder_.dispose();
        baseResponseBuilder_ = null;
      }
      if (metricsBuilder_ == null) {
        metrics_ = java.util.Collections.emptyList();
      } else {
        metrics_ = null;
        metricsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      insights_ = null;
      if (insightsBuilder_ != null) {
        insightsBuilder_.dispose();
        insightsBuilder_ = null;
      }
      generatedAt_ = null;
      if (generatedAtBuilder_ != null) {
        generatedAtBuilder_.dispose();
        generatedAtBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.movieplatform.proto.notification.NotificationReqResProto.internal_static_proto_notification_GetNotificationAnalyticsResponse_descriptor;
    }

    @java.lang.Override
    public com.movieplatform.proto.notification.GetNotificationAnalyticsResponse getDefaultInstanceForType() {
      return com.movieplatform.proto.notification.GetNotificationAnalyticsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.movieplatform.proto.notification.GetNotificationAnalyticsResponse build() {
      com.movieplatform.proto.notification.GetNotificationAnalyticsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.movieplatform.proto.notification.GetNotificationAnalyticsResponse buildPartial() {
      com.movieplatform.proto.notification.GetNotificationAnalyticsResponse result = new com.movieplatform.proto.notification.GetNotificationAnalyticsResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.movieplatform.proto.notification.GetNotificationAnalyticsResponse result) {
      if (metricsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          metrics_ = java.util.Collections.unmodifiableList(metrics_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.metrics_ = metrics_;
      } else {
        result.metrics_ = metricsBuilder_.build();
      }
    }

    private void buildPartial0(com.movieplatform.proto.notification.GetNotificationAnalyticsResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.baseResponse_ = baseResponseBuilder_ == null
            ? baseResponse_
            : baseResponseBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.insights_ = insightsBuilder_ == null
            ? insights_
            : insightsBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.generatedAt_ = generatedAtBuilder_ == null
            ? generatedAt_
            : generatedAtBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.movieplatform.proto.notification.GetNotificationAnalyticsResponse) {
        return mergeFrom((com.movieplatform.proto.notification.GetNotificationAnalyticsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.movieplatform.proto.notification.GetNotificationAnalyticsResponse other) {
      if (other == com.movieplatform.proto.notification.GetNotificationAnalyticsResponse.getDefaultInstance()) return this;
      if (other.hasBaseResponse()) {
        mergeBaseResponse(other.getBaseResponse());
      }
      if (metricsBuilder_ == null) {
        if (!other.metrics_.isEmpty()) {
          if (metrics_.isEmpty()) {
            metrics_ = other.metrics_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureMetricsIsMutable();
            metrics_.addAll(other.metrics_);
          }
          onChanged();
        }
      } else {
        if (!other.metrics_.isEmpty()) {
          if (metricsBuilder_.isEmpty()) {
            metricsBuilder_.dispose();
            metricsBuilder_ = null;
            metrics_ = other.metrics_;
            bitField0_ = (bitField0_ & ~0x00000002);
            metricsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetMetricsFieldBuilder() : null;
          } else {
            metricsBuilder_.addAllMessages(other.metrics_);
          }
        }
      }
      if (other.hasInsights()) {
        mergeInsights(other.getInsights());
      }
      if (other.hasGeneratedAt()) {
        mergeGeneratedAt(other.getGeneratedAt());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetBaseResponseFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.movieplatform.proto.notification.AnalyticsMetric m =
                  input.readMessage(
                      com.movieplatform.proto.notification.AnalyticsMetric.parser(),
                      extensionRegistry);
              if (metricsBuilder_ == null) {
                ensureMetricsIsMutable();
                metrics_.add(m);
              } else {
                metricsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetInsightsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetGeneratedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.movieplatform.proto.common.BaseResponse baseResponse_;
    private com.google.protobuf.SingleFieldBuilder<
        com.movieplatform.proto.common.BaseResponse, com.movieplatform.proto.common.BaseResponse.Builder, com.movieplatform.proto.common.BaseResponseOrBuilder> baseResponseBuilder_;
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     * @return Whether the baseResponse field is set.
     */
    public boolean hasBaseResponse() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     * @return The baseResponse.
     */
    public com.movieplatform.proto.common.BaseResponse getBaseResponse() {
      if (baseResponseBuilder_ == null) {
        return baseResponse_ == null ? com.movieplatform.proto.common.BaseResponse.getDefaultInstance() : baseResponse_;
      } else {
        return baseResponseBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public Builder setBaseResponse(com.movieplatform.proto.common.BaseResponse value) {
      if (baseResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        baseResponse_ = value;
      } else {
        baseResponseBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public Builder setBaseResponse(
        com.movieplatform.proto.common.BaseResponse.Builder builderForValue) {
      if (baseResponseBuilder_ == null) {
        baseResponse_ = builderForValue.build();
      } else {
        baseResponseBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public Builder mergeBaseResponse(com.movieplatform.proto.common.BaseResponse value) {
      if (baseResponseBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          baseResponse_ != null &&
          baseResponse_ != com.movieplatform.proto.common.BaseResponse.getDefaultInstance()) {
          getBaseResponseBuilder().mergeFrom(value);
        } else {
          baseResponse_ = value;
        }
      } else {
        baseResponseBuilder_.mergeFrom(value);
      }
      if (baseResponse_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public Builder clearBaseResponse() {
      bitField0_ = (bitField0_ & ~0x00000001);
      baseResponse_ = null;
      if (baseResponseBuilder_ != null) {
        baseResponseBuilder_.dispose();
        baseResponseBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public com.movieplatform.proto.common.BaseResponse.Builder getBaseResponseBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetBaseResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public com.movieplatform.proto.common.BaseResponseOrBuilder getBaseResponseOrBuilder() {
      if (baseResponseBuilder_ != null) {
        return baseResponseBuilder_.getMessageOrBuilder();
      } else {
        return baseResponse_ == null ?
            com.movieplatform.proto.common.BaseResponse.getDefaultInstance() : baseResponse_;
      }
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.movieplatform.proto.common.BaseResponse, com.movieplatform.proto.common.BaseResponse.Builder, com.movieplatform.proto.common.BaseResponseOrBuilder> 
        internalGetBaseResponseFieldBuilder() {
      if (baseResponseBuilder_ == null) {
        baseResponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.movieplatform.proto.common.BaseResponse, com.movieplatform.proto.common.BaseResponse.Builder, com.movieplatform.proto.common.BaseResponseOrBuilder>(
                getBaseResponse(),
                getParentForChildren(),
                isClean());
        baseResponse_ = null;
      }
      return baseResponseBuilder_;
    }

    private java.util.List<com.movieplatform.proto.notification.AnalyticsMetric> metrics_ =
      java.util.Collections.emptyList();
    private void ensureMetricsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        metrics_ = new java.util.ArrayList<com.movieplatform.proto.notification.AnalyticsMetric>(metrics_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.movieplatform.proto.notification.AnalyticsMetric, com.movieplatform.proto.notification.AnalyticsMetric.Builder, com.movieplatform.proto.notification.AnalyticsMetricOrBuilder> metricsBuilder_;

    /**
     * <pre>
     * Analytics metrics
     * </pre>
     *
     * <code>repeated .proto.notification.AnalyticsMetric metrics = 2;</code>
     */
    public java.util.List<com.movieplatform.proto.notification.AnalyticsMetric> getMetricsList() {
      if (metricsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(metrics_);
      } else {
        return metricsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Analytics metrics
     * </pre>
     *
     * <code>repeated .proto.notification.AnalyticsMetric metrics = 2;</code>
     */
    public int getMetricsCount() {
      if (metricsBuilder_ == null) {
        return metrics_.size();
      } else {
        return metricsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Analytics metrics
     * </pre>
     *
     * <code>repeated .proto.notification.AnalyticsMetric metrics = 2;</code>
     */
    public com.movieplatform.proto.notification.AnalyticsMetric getMetrics(int index) {
      if (metricsBuilder_ == null) {
        return metrics_.get(index);
      } else {
        return metricsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Analytics metrics
     * </pre>
     *
     * <code>repeated .proto.notification.AnalyticsMetric metrics = 2;</code>
     */
    public Builder setMetrics(
        int index, com.movieplatform.proto.notification.AnalyticsMetric value) {
      if (metricsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMetricsIsMutable();
        metrics_.set(index, value);
        onChanged();
      } else {
        metricsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Analytics metrics
     * </pre>
     *
     * <code>repeated .proto.notification.AnalyticsMetric metrics = 2;</code>
     */
    public Builder setMetrics(
        int index, com.movieplatform.proto.notification.AnalyticsMetric.Builder builderForValue) {
      if (metricsBuilder_ == null) {
        ensureMetricsIsMutable();
        metrics_.set(index, builderForValue.build());
        onChanged();
      } else {
        metricsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Analytics metrics
     * </pre>
     *
     * <code>repeated .proto.notification.AnalyticsMetric metrics = 2;</code>
     */
    public Builder addMetrics(com.movieplatform.proto.notification.AnalyticsMetric value) {
      if (metricsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMetricsIsMutable();
        metrics_.add(value);
        onChanged();
      } else {
        metricsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Analytics metrics
     * </pre>
     *
     * <code>repeated .proto.notification.AnalyticsMetric metrics = 2;</code>
     */
    public Builder addMetrics(
        int index, com.movieplatform.proto.notification.AnalyticsMetric value) {
      if (metricsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMetricsIsMutable();
        metrics_.add(index, value);
        onChanged();
      } else {
        metricsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Analytics metrics
     * </pre>
     *
     * <code>repeated .proto.notification.AnalyticsMetric metrics = 2;</code>
     */
    public Builder addMetrics(
        com.movieplatform.proto.notification.AnalyticsMetric.Builder builderForValue) {
      if (metricsBuilder_ == null) {
        ensureMetricsIsMutable();
        metrics_.add(builderForValue.build());
        onChanged();
      } else {
        metricsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Analytics metrics
     * </pre>
     *
     * <code>repeated .proto.notification.AnalyticsMetric metrics = 2;</code>
     */
    public Builder addMetrics(
        int index, com.movieplatform.proto.notification.AnalyticsMetric.Builder builderForValue) {
      if (metricsBuilder_ == null) {
        ensureMetricsIsMutable();
        metrics_.add(index, builderForValue.build());
        onChanged();
      } else {
        metricsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Analytics metrics
     * </pre>
     *
     * <code>repeated .proto.notification.AnalyticsMetric metrics = 2;</code>
     */
    public Builder addAllMetrics(
        java.lang.Iterable<? extends com.movieplatform.proto.notification.AnalyticsMetric> values) {
      if (metricsBuilder_ == null) {
        ensureMetricsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, metrics_);
        onChanged();
      } else {
        metricsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Analytics metrics
     * </pre>
     *
     * <code>repeated .proto.notification.AnalyticsMetric metrics = 2;</code>
     */
    public Builder clearMetrics() {
      if (metricsBuilder_ == null) {
        metrics_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        metricsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Analytics metrics
     * </pre>
     *
     * <code>repeated .proto.notification.AnalyticsMetric metrics = 2;</code>
     */
    public Builder removeMetrics(int index) {
      if (metricsBuilder_ == null) {
        ensureMetricsIsMutable();
        metrics_.remove(index);
        onChanged();
      } else {
        metricsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Analytics metrics
     * </pre>
     *
     * <code>repeated .proto.notification.AnalyticsMetric metrics = 2;</code>
     */
    public com.movieplatform.proto.notification.AnalyticsMetric.Builder getMetricsBuilder(
        int index) {
      return internalGetMetricsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Analytics metrics
     * </pre>
     *
     * <code>repeated .proto.notification.AnalyticsMetric metrics = 2;</code>
     */
    public com.movieplatform.proto.notification.AnalyticsMetricOrBuilder getMetricsOrBuilder(
        int index) {
      if (metricsBuilder_ == null) {
        return metrics_.get(index);  } else {
        return metricsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Analytics metrics
     * </pre>
     *
     * <code>repeated .proto.notification.AnalyticsMetric metrics = 2;</code>
     */
    public java.util.List<? extends com.movieplatform.proto.notification.AnalyticsMetricOrBuilder> 
         getMetricsOrBuilderList() {
      if (metricsBuilder_ != null) {
        return metricsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(metrics_);
      }
    }
    /**
     * <pre>
     * Analytics metrics
     * </pre>
     *
     * <code>repeated .proto.notification.AnalyticsMetric metrics = 2;</code>
     */
    public com.movieplatform.proto.notification.AnalyticsMetric.Builder addMetricsBuilder() {
      return internalGetMetricsFieldBuilder().addBuilder(
          com.movieplatform.proto.notification.AnalyticsMetric.getDefaultInstance());
    }
    /**
     * <pre>
     * Analytics metrics
     * </pre>
     *
     * <code>repeated .proto.notification.AnalyticsMetric metrics = 2;</code>
     */
    public com.movieplatform.proto.notification.AnalyticsMetric.Builder addMetricsBuilder(
        int index) {
      return internalGetMetricsFieldBuilder().addBuilder(
          index, com.movieplatform.proto.notification.AnalyticsMetric.getDefaultInstance());
    }
    /**
     * <pre>
     * Analytics metrics
     * </pre>
     *
     * <code>repeated .proto.notification.AnalyticsMetric metrics = 2;</code>
     */
    public java.util.List<com.movieplatform.proto.notification.AnalyticsMetric.Builder> 
         getMetricsBuilderList() {
      return internalGetMetricsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.movieplatform.proto.notification.AnalyticsMetric, com.movieplatform.proto.notification.AnalyticsMetric.Builder, com.movieplatform.proto.notification.AnalyticsMetricOrBuilder> 
        internalGetMetricsFieldBuilder() {
      if (metricsBuilder_ == null) {
        metricsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.movieplatform.proto.notification.AnalyticsMetric, com.movieplatform.proto.notification.AnalyticsMetric.Builder, com.movieplatform.proto.notification.AnalyticsMetricOrBuilder>(
                metrics_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        metrics_ = null;
      }
      return metricsBuilder_;
    }

    private com.movieplatform.proto.notification.NotificationInsights insights_;
    private com.google.protobuf.SingleFieldBuilder<
        com.movieplatform.proto.notification.NotificationInsights, com.movieplatform.proto.notification.NotificationInsights.Builder, com.movieplatform.proto.notification.NotificationInsightsOrBuilder> insightsBuilder_;
    /**
     * <pre>
     * Notification insights
     * </pre>
     *
     * <code>.proto.notification.NotificationInsights insights = 3;</code>
     * @return Whether the insights field is set.
     */
    public boolean hasInsights() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Notification insights
     * </pre>
     *
     * <code>.proto.notification.NotificationInsights insights = 3;</code>
     * @return The insights.
     */
    public com.movieplatform.proto.notification.NotificationInsights getInsights() {
      if (insightsBuilder_ == null) {
        return insights_ == null ? com.movieplatform.proto.notification.NotificationInsights.getDefaultInstance() : insights_;
      } else {
        return insightsBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Notification insights
     * </pre>
     *
     * <code>.proto.notification.NotificationInsights insights = 3;</code>
     */
    public Builder setInsights(com.movieplatform.proto.notification.NotificationInsights value) {
      if (insightsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        insights_ = value;
      } else {
        insightsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Notification insights
     * </pre>
     *
     * <code>.proto.notification.NotificationInsights insights = 3;</code>
     */
    public Builder setInsights(
        com.movieplatform.proto.notification.NotificationInsights.Builder builderForValue) {
      if (insightsBuilder_ == null) {
        insights_ = builderForValue.build();
      } else {
        insightsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Notification insights
     * </pre>
     *
     * <code>.proto.notification.NotificationInsights insights = 3;</code>
     */
    public Builder mergeInsights(com.movieplatform.proto.notification.NotificationInsights value) {
      if (insightsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          insights_ != null &&
          insights_ != com.movieplatform.proto.notification.NotificationInsights.getDefaultInstance()) {
          getInsightsBuilder().mergeFrom(value);
        } else {
          insights_ = value;
        }
      } else {
        insightsBuilder_.mergeFrom(value);
      }
      if (insights_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Notification insights
     * </pre>
     *
     * <code>.proto.notification.NotificationInsights insights = 3;</code>
     */
    public Builder clearInsights() {
      bitField0_ = (bitField0_ & ~0x00000004);
      insights_ = null;
      if (insightsBuilder_ != null) {
        insightsBuilder_.dispose();
        insightsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Notification insights
     * </pre>
     *
     * <code>.proto.notification.NotificationInsights insights = 3;</code>
     */
    public com.movieplatform.proto.notification.NotificationInsights.Builder getInsightsBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetInsightsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Notification insights
     * </pre>
     *
     * <code>.proto.notification.NotificationInsights insights = 3;</code>
     */
    public com.movieplatform.proto.notification.NotificationInsightsOrBuilder getInsightsOrBuilder() {
      if (insightsBuilder_ != null) {
        return insightsBuilder_.getMessageOrBuilder();
      } else {
        return insights_ == null ?
            com.movieplatform.proto.notification.NotificationInsights.getDefaultInstance() : insights_;
      }
    }
    /**
     * <pre>
     * Notification insights
     * </pre>
     *
     * <code>.proto.notification.NotificationInsights insights = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.movieplatform.proto.notification.NotificationInsights, com.movieplatform.proto.notification.NotificationInsights.Builder, com.movieplatform.proto.notification.NotificationInsightsOrBuilder> 
        internalGetInsightsFieldBuilder() {
      if (insightsBuilder_ == null) {
        insightsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.movieplatform.proto.notification.NotificationInsights, com.movieplatform.proto.notification.NotificationInsights.Builder, com.movieplatform.proto.notification.NotificationInsightsOrBuilder>(
                getInsights(),
                getParentForChildren(),
                isClean());
        insights_ = null;
      }
      return insightsBuilder_;
    }

    private com.movieplatform.proto.common.DateTime generatedAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.movieplatform.proto.common.DateTime, com.movieplatform.proto.common.DateTime.Builder, com.movieplatform.proto.common.DateTimeOrBuilder> generatedAtBuilder_;
    /**
     * <pre>
     * When analytics were generated
     * </pre>
     *
     * <code>.proto.common.DateTime generated_at = 4;</code>
     * @return Whether the generatedAt field is set.
     */
    public boolean hasGeneratedAt() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * When analytics were generated
     * </pre>
     *
     * <code>.proto.common.DateTime generated_at = 4;</code>
     * @return The generatedAt.
     */
    public com.movieplatform.proto.common.DateTime getGeneratedAt() {
      if (generatedAtBuilder_ == null) {
        return generatedAt_ == null ? com.movieplatform.proto.common.DateTime.getDefaultInstance() : generatedAt_;
      } else {
        return generatedAtBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * When analytics were generated
     * </pre>
     *
     * <code>.proto.common.DateTime generated_at = 4;</code>
     */
    public Builder setGeneratedAt(com.movieplatform.proto.common.DateTime value) {
      if (generatedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        generatedAt_ = value;
      } else {
        generatedAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * When analytics were generated
     * </pre>
     *
     * <code>.proto.common.DateTime generated_at = 4;</code>
     */
    public Builder setGeneratedAt(
        com.movieplatform.proto.common.DateTime.Builder builderForValue) {
      if (generatedAtBuilder_ == null) {
        generatedAt_ = builderForValue.build();
      } else {
        generatedAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * When analytics were generated
     * </pre>
     *
     * <code>.proto.common.DateTime generated_at = 4;</code>
     */
    public Builder mergeGeneratedAt(com.movieplatform.proto.common.DateTime value) {
      if (generatedAtBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          generatedAt_ != null &&
          generatedAt_ != com.movieplatform.proto.common.DateTime.getDefaultInstance()) {
          getGeneratedAtBuilder().mergeFrom(value);
        } else {
          generatedAt_ = value;
        }
      } else {
        generatedAtBuilder_.mergeFrom(value);
      }
      if (generatedAt_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * When analytics were generated
     * </pre>
     *
     * <code>.proto.common.DateTime generated_at = 4;</code>
     */
    public Builder clearGeneratedAt() {
      bitField0_ = (bitField0_ & ~0x00000008);
      generatedAt_ = null;
      if (generatedAtBuilder_ != null) {
        generatedAtBuilder_.dispose();
        generatedAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * When analytics were generated
     * </pre>
     *
     * <code>.proto.common.DateTime generated_at = 4;</code>
     */
    public com.movieplatform.proto.common.DateTime.Builder getGeneratedAtBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return internalGetGeneratedAtFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * When analytics were generated
     * </pre>
     *
     * <code>.proto.common.DateTime generated_at = 4;</code>
     */
    public com.movieplatform.proto.common.DateTimeOrBuilder getGeneratedAtOrBuilder() {
      if (generatedAtBuilder_ != null) {
        return generatedAtBuilder_.getMessageOrBuilder();
      } else {
        return generatedAt_ == null ?
            com.movieplatform.proto.common.DateTime.getDefaultInstance() : generatedAt_;
      }
    }
    /**
     * <pre>
     * When analytics were generated
     * </pre>
     *
     * <code>.proto.common.DateTime generated_at = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.movieplatform.proto.common.DateTime, com.movieplatform.proto.common.DateTime.Builder, com.movieplatform.proto.common.DateTimeOrBuilder> 
        internalGetGeneratedAtFieldBuilder() {
      if (generatedAtBuilder_ == null) {
        generatedAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.movieplatform.proto.common.DateTime, com.movieplatform.proto.common.DateTime.Builder, com.movieplatform.proto.common.DateTimeOrBuilder>(
                getGeneratedAt(),
                getParentForChildren(),
                isClean());
        generatedAt_ = null;
      }
      return generatedAtBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:proto.notification.GetNotificationAnalyticsResponse)
  }

  // @@protoc_insertion_point(class_scope:proto.notification.GetNotificationAnalyticsResponse)
  private static final com.movieplatform.proto.notification.GetNotificationAnalyticsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.movieplatform.proto.notification.GetNotificationAnalyticsResponse();
  }

  public static com.movieplatform.proto.notification.GetNotificationAnalyticsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetNotificationAnalyticsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetNotificationAnalyticsResponse>() {
    @java.lang.Override
    public GetNotificationAnalyticsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetNotificationAnalyticsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetNotificationAnalyticsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.movieplatform.proto.notification.GetNotificationAnalyticsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

