// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notification/notification_req_res.proto
// Protobuf Java Version: 4.30.2

package com.movieplatform.proto.notification;

public interface GetPushDeliveryStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.notification.GetPushDeliveryStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   * @return Whether the baseResponse field is set.
   */
  boolean hasBaseResponse();
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   * @return The baseResponse.
   */
  com.movieplatform.proto.common.BaseResponse getBaseResponse();
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   */
  com.movieplatform.proto.common.BaseResponseOrBuilder getBaseResponseOrBuilder();

  /**
   * <pre>
   * Push delivery status
   * </pre>
   *
   * <code>.proto.notification.PushDeliveryStatus delivery_status = 2;</code>
   * @return Whether the deliveryStatus field is set.
   */
  boolean hasDeliveryStatus();
  /**
   * <pre>
   * Push delivery status
   * </pre>
   *
   * <code>.proto.notification.PushDeliveryStatus delivery_status = 2;</code>
   * @return The deliveryStatus.
   */
  com.movieplatform.proto.notification.PushDeliveryStatus getDeliveryStatus();
  /**
   * <pre>
   * Push delivery status
   * </pre>
   *
   * <code>.proto.notification.PushDeliveryStatus delivery_status = 2;</code>
   */
  com.movieplatform.proto.notification.PushDeliveryStatusOrBuilder getDeliveryStatusOrBuilder();
}
