// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notification/notification_req_res.proto
// Protobuf Java Version: 4.30.2

package com.movieplatform.proto.notification;

/**
 * <pre>
 * Get push delivery status response
 * </pre>
 *
 * Protobuf type {@code proto.notification.GetPushDeliveryStatusResponse}
 */
public final class GetPushDeliveryStatusResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:proto.notification.GetPushDeliveryStatusResponse)
    GetPushDeliveryStatusResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      GetPushDeliveryStatusResponse.class.getName());
  }
  // Use GetPushDeliveryStatusResponse.newBuilder() to construct.
  private GetPushDeliveryStatusResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetPushDeliveryStatusResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.movieplatform.proto.notification.NotificationReqResProto.internal_static_proto_notification_GetPushDeliveryStatusResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.movieplatform.proto.notification.NotificationReqResProto.internal_static_proto_notification_GetPushDeliveryStatusResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.movieplatform.proto.notification.GetPushDeliveryStatusResponse.class, com.movieplatform.proto.notification.GetPushDeliveryStatusResponse.Builder.class);
  }

  private int bitField0_;
  public static final int BASE_RESPONSE_FIELD_NUMBER = 1;
  private com.movieplatform.proto.common.BaseResponse baseResponse_;
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   * @return Whether the baseResponse field is set.
   */
  @java.lang.Override
  public boolean hasBaseResponse() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   * @return The baseResponse.
   */
  @java.lang.Override
  public com.movieplatform.proto.common.BaseResponse getBaseResponse() {
    return baseResponse_ == null ? com.movieplatform.proto.common.BaseResponse.getDefaultInstance() : baseResponse_;
  }
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   */
  @java.lang.Override
  public com.movieplatform.proto.common.BaseResponseOrBuilder getBaseResponseOrBuilder() {
    return baseResponse_ == null ? com.movieplatform.proto.common.BaseResponse.getDefaultInstance() : baseResponse_;
  }

  public static final int DELIVERY_STATUS_FIELD_NUMBER = 2;
  private com.movieplatform.proto.notification.PushDeliveryStatus deliveryStatus_;
  /**
   * <pre>
   * Push delivery status
   * </pre>
   *
   * <code>.proto.notification.PushDeliveryStatus delivery_status = 2;</code>
   * @return Whether the deliveryStatus field is set.
   */
  @java.lang.Override
  public boolean hasDeliveryStatus() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Push delivery status
   * </pre>
   *
   * <code>.proto.notification.PushDeliveryStatus delivery_status = 2;</code>
   * @return The deliveryStatus.
   */
  @java.lang.Override
  public com.movieplatform.proto.notification.PushDeliveryStatus getDeliveryStatus() {
    return deliveryStatus_ == null ? com.movieplatform.proto.notification.PushDeliveryStatus.getDefaultInstance() : deliveryStatus_;
  }
  /**
   * <pre>
   * Push delivery status
   * </pre>
   *
   * <code>.proto.notification.PushDeliveryStatus delivery_status = 2;</code>
   */
  @java.lang.Override
  public com.movieplatform.proto.notification.PushDeliveryStatusOrBuilder getDeliveryStatusOrBuilder() {
    return deliveryStatus_ == null ? com.movieplatform.proto.notification.PushDeliveryStatus.getDefaultInstance() : deliveryStatus_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getBaseResponse());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getDeliveryStatus());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBaseResponse());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getDeliveryStatus());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.movieplatform.proto.notification.GetPushDeliveryStatusResponse)) {
      return super.equals(obj);
    }
    com.movieplatform.proto.notification.GetPushDeliveryStatusResponse other = (com.movieplatform.proto.notification.GetPushDeliveryStatusResponse) obj;

    if (hasBaseResponse() != other.hasBaseResponse()) return false;
    if (hasBaseResponse()) {
      if (!getBaseResponse()
          .equals(other.getBaseResponse())) return false;
    }
    if (hasDeliveryStatus() != other.hasDeliveryStatus()) return false;
    if (hasDeliveryStatus()) {
      if (!getDeliveryStatus()
          .equals(other.getDeliveryStatus())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBaseResponse()) {
      hash = (37 * hash) + BASE_RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getBaseResponse().hashCode();
    }
    if (hasDeliveryStatus()) {
      hash = (37 * hash) + DELIVERY_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getDeliveryStatus().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.movieplatform.proto.notification.GetPushDeliveryStatusResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.notification.GetPushDeliveryStatusResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.notification.GetPushDeliveryStatusResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.notification.GetPushDeliveryStatusResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.notification.GetPushDeliveryStatusResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.notification.GetPushDeliveryStatusResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.notification.GetPushDeliveryStatusResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.notification.GetPushDeliveryStatusResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.movieplatform.proto.notification.GetPushDeliveryStatusResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.movieplatform.proto.notification.GetPushDeliveryStatusResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.movieplatform.proto.notification.GetPushDeliveryStatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.notification.GetPushDeliveryStatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.movieplatform.proto.notification.GetPushDeliveryStatusResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Get push delivery status response
   * </pre>
   *
   * Protobuf type {@code proto.notification.GetPushDeliveryStatusResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.notification.GetPushDeliveryStatusResponse)
      com.movieplatform.proto.notification.GetPushDeliveryStatusResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.movieplatform.proto.notification.NotificationReqResProto.internal_static_proto_notification_GetPushDeliveryStatusResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.movieplatform.proto.notification.NotificationReqResProto.internal_static_proto_notification_GetPushDeliveryStatusResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.movieplatform.proto.notification.GetPushDeliveryStatusResponse.class, com.movieplatform.proto.notification.GetPushDeliveryStatusResponse.Builder.class);
    }

    // Construct using com.movieplatform.proto.notification.GetPushDeliveryStatusResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetBaseResponseFieldBuilder();
        internalGetDeliveryStatusFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      baseResponse_ = null;
      if (baseResponseBuilder_ != null) {
        baseResponseBuilder_.dispose();
        baseResponseBuilder_ = null;
      }
      deliveryStatus_ = null;
      if (deliveryStatusBuilder_ != null) {
        deliveryStatusBuilder_.dispose();
        deliveryStatusBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.movieplatform.proto.notification.NotificationReqResProto.internal_static_proto_notification_GetPushDeliveryStatusResponse_descriptor;
    }

    @java.lang.Override
    public com.movieplatform.proto.notification.GetPushDeliveryStatusResponse getDefaultInstanceForType() {
      return com.movieplatform.proto.notification.GetPushDeliveryStatusResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.movieplatform.proto.notification.GetPushDeliveryStatusResponse build() {
      com.movieplatform.proto.notification.GetPushDeliveryStatusResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.movieplatform.proto.notification.GetPushDeliveryStatusResponse buildPartial() {
      com.movieplatform.proto.notification.GetPushDeliveryStatusResponse result = new com.movieplatform.proto.notification.GetPushDeliveryStatusResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.movieplatform.proto.notification.GetPushDeliveryStatusResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.baseResponse_ = baseResponseBuilder_ == null
            ? baseResponse_
            : baseResponseBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.deliveryStatus_ = deliveryStatusBuilder_ == null
            ? deliveryStatus_
            : deliveryStatusBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.movieplatform.proto.notification.GetPushDeliveryStatusResponse) {
        return mergeFrom((com.movieplatform.proto.notification.GetPushDeliveryStatusResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.movieplatform.proto.notification.GetPushDeliveryStatusResponse other) {
      if (other == com.movieplatform.proto.notification.GetPushDeliveryStatusResponse.getDefaultInstance()) return this;
      if (other.hasBaseResponse()) {
        mergeBaseResponse(other.getBaseResponse());
      }
      if (other.hasDeliveryStatus()) {
        mergeDeliveryStatus(other.getDeliveryStatus());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetBaseResponseFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetDeliveryStatusFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.movieplatform.proto.common.BaseResponse baseResponse_;
    private com.google.protobuf.SingleFieldBuilder<
        com.movieplatform.proto.common.BaseResponse, com.movieplatform.proto.common.BaseResponse.Builder, com.movieplatform.proto.common.BaseResponseOrBuilder> baseResponseBuilder_;
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     * @return Whether the baseResponse field is set.
     */
    public boolean hasBaseResponse() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     * @return The baseResponse.
     */
    public com.movieplatform.proto.common.BaseResponse getBaseResponse() {
      if (baseResponseBuilder_ == null) {
        return baseResponse_ == null ? com.movieplatform.proto.common.BaseResponse.getDefaultInstance() : baseResponse_;
      } else {
        return baseResponseBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public Builder setBaseResponse(com.movieplatform.proto.common.BaseResponse value) {
      if (baseResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        baseResponse_ = value;
      } else {
        baseResponseBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public Builder setBaseResponse(
        com.movieplatform.proto.common.BaseResponse.Builder builderForValue) {
      if (baseResponseBuilder_ == null) {
        baseResponse_ = builderForValue.build();
      } else {
        baseResponseBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public Builder mergeBaseResponse(com.movieplatform.proto.common.BaseResponse value) {
      if (baseResponseBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          baseResponse_ != null &&
          baseResponse_ != com.movieplatform.proto.common.BaseResponse.getDefaultInstance()) {
          getBaseResponseBuilder().mergeFrom(value);
        } else {
          baseResponse_ = value;
        }
      } else {
        baseResponseBuilder_.mergeFrom(value);
      }
      if (baseResponse_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public Builder clearBaseResponse() {
      bitField0_ = (bitField0_ & ~0x00000001);
      baseResponse_ = null;
      if (baseResponseBuilder_ != null) {
        baseResponseBuilder_.dispose();
        baseResponseBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public com.movieplatform.proto.common.BaseResponse.Builder getBaseResponseBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetBaseResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public com.movieplatform.proto.common.BaseResponseOrBuilder getBaseResponseOrBuilder() {
      if (baseResponseBuilder_ != null) {
        return baseResponseBuilder_.getMessageOrBuilder();
      } else {
        return baseResponse_ == null ?
            com.movieplatform.proto.common.BaseResponse.getDefaultInstance() : baseResponse_;
      }
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.movieplatform.proto.common.BaseResponse, com.movieplatform.proto.common.BaseResponse.Builder, com.movieplatform.proto.common.BaseResponseOrBuilder> 
        internalGetBaseResponseFieldBuilder() {
      if (baseResponseBuilder_ == null) {
        baseResponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.movieplatform.proto.common.BaseResponse, com.movieplatform.proto.common.BaseResponse.Builder, com.movieplatform.proto.common.BaseResponseOrBuilder>(
                getBaseResponse(),
                getParentForChildren(),
                isClean());
        baseResponse_ = null;
      }
      return baseResponseBuilder_;
    }

    private com.movieplatform.proto.notification.PushDeliveryStatus deliveryStatus_;
    private com.google.protobuf.SingleFieldBuilder<
        com.movieplatform.proto.notification.PushDeliveryStatus, com.movieplatform.proto.notification.PushDeliveryStatus.Builder, com.movieplatform.proto.notification.PushDeliveryStatusOrBuilder> deliveryStatusBuilder_;
    /**
     * <pre>
     * Push delivery status
     * </pre>
     *
     * <code>.proto.notification.PushDeliveryStatus delivery_status = 2;</code>
     * @return Whether the deliveryStatus field is set.
     */
    public boolean hasDeliveryStatus() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Push delivery status
     * </pre>
     *
     * <code>.proto.notification.PushDeliveryStatus delivery_status = 2;</code>
     * @return The deliveryStatus.
     */
    public com.movieplatform.proto.notification.PushDeliveryStatus getDeliveryStatus() {
      if (deliveryStatusBuilder_ == null) {
        return deliveryStatus_ == null ? com.movieplatform.proto.notification.PushDeliveryStatus.getDefaultInstance() : deliveryStatus_;
      } else {
        return deliveryStatusBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Push delivery status
     * </pre>
     *
     * <code>.proto.notification.PushDeliveryStatus delivery_status = 2;</code>
     */
    public Builder setDeliveryStatus(com.movieplatform.proto.notification.PushDeliveryStatus value) {
      if (deliveryStatusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        deliveryStatus_ = value;
      } else {
        deliveryStatusBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Push delivery status
     * </pre>
     *
     * <code>.proto.notification.PushDeliveryStatus delivery_status = 2;</code>
     */
    public Builder setDeliveryStatus(
        com.movieplatform.proto.notification.PushDeliveryStatus.Builder builderForValue) {
      if (deliveryStatusBuilder_ == null) {
        deliveryStatus_ = builderForValue.build();
      } else {
        deliveryStatusBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Push delivery status
     * </pre>
     *
     * <code>.proto.notification.PushDeliveryStatus delivery_status = 2;</code>
     */
    public Builder mergeDeliveryStatus(com.movieplatform.proto.notification.PushDeliveryStatus value) {
      if (deliveryStatusBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          deliveryStatus_ != null &&
          deliveryStatus_ != com.movieplatform.proto.notification.PushDeliveryStatus.getDefaultInstance()) {
          getDeliveryStatusBuilder().mergeFrom(value);
        } else {
          deliveryStatus_ = value;
        }
      } else {
        deliveryStatusBuilder_.mergeFrom(value);
      }
      if (deliveryStatus_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Push delivery status
     * </pre>
     *
     * <code>.proto.notification.PushDeliveryStatus delivery_status = 2;</code>
     */
    public Builder clearDeliveryStatus() {
      bitField0_ = (bitField0_ & ~0x00000002);
      deliveryStatus_ = null;
      if (deliveryStatusBuilder_ != null) {
        deliveryStatusBuilder_.dispose();
        deliveryStatusBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Push delivery status
     * </pre>
     *
     * <code>.proto.notification.PushDeliveryStatus delivery_status = 2;</code>
     */
    public com.movieplatform.proto.notification.PushDeliveryStatus.Builder getDeliveryStatusBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetDeliveryStatusFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Push delivery status
     * </pre>
     *
     * <code>.proto.notification.PushDeliveryStatus delivery_status = 2;</code>
     */
    public com.movieplatform.proto.notification.PushDeliveryStatusOrBuilder getDeliveryStatusOrBuilder() {
      if (deliveryStatusBuilder_ != null) {
        return deliveryStatusBuilder_.getMessageOrBuilder();
      } else {
        return deliveryStatus_ == null ?
            com.movieplatform.proto.notification.PushDeliveryStatus.getDefaultInstance() : deliveryStatus_;
      }
    }
    /**
     * <pre>
     * Push delivery status
     * </pre>
     *
     * <code>.proto.notification.PushDeliveryStatus delivery_status = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.movieplatform.proto.notification.PushDeliveryStatus, com.movieplatform.proto.notification.PushDeliveryStatus.Builder, com.movieplatform.proto.notification.PushDeliveryStatusOrBuilder> 
        internalGetDeliveryStatusFieldBuilder() {
      if (deliveryStatusBuilder_ == null) {
        deliveryStatusBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.movieplatform.proto.notification.PushDeliveryStatus, com.movieplatform.proto.notification.PushDeliveryStatus.Builder, com.movieplatform.proto.notification.PushDeliveryStatusOrBuilder>(
                getDeliveryStatus(),
                getParentForChildren(),
                isClean());
        deliveryStatus_ = null;
      }
      return deliveryStatusBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:proto.notification.GetPushDeliveryStatusResponse)
  }

  // @@protoc_insertion_point(class_scope:proto.notification.GetPushDeliveryStatusResponse)
  private static final com.movieplatform.proto.notification.GetPushDeliveryStatusResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.movieplatform.proto.notification.GetPushDeliveryStatusResponse();
  }

  public static com.movieplatform.proto.notification.GetPushDeliveryStatusResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetPushDeliveryStatusResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetPushDeliveryStatusResponse>() {
    @java.lang.Override
    public GetPushDeliveryStatusResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetPushDeliveryStatusResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetPushDeliveryStatusResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.movieplatform.proto.notification.GetPushDeliveryStatusResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

