// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notification/notification_req_res.proto
// Protobuf Java Version: 4.30.2

package com.movieplatform.proto.notification;

/**
 * <pre>
 * Get user notifications response
 * </pre>
 *
 * Protobuf type {@code proto.notification.GetUserNotificationsResponse}
 */
public final class GetUserNotificationsResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:proto.notification.GetUserNotificationsResponse)
    GetUserNotificationsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      GetUserNotificationsResponse.class.getName());
  }
  // Use GetUserNotificationsResponse.newBuilder() to construct.
  private GetUserNotificationsResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetUserNotificationsResponse() {
    notifications_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.movieplatform.proto.notification.NotificationReqResProto.internal_static_proto_notification_GetUserNotificationsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.movieplatform.proto.notification.NotificationReqResProto.internal_static_proto_notification_GetUserNotificationsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.movieplatform.proto.notification.GetUserNotificationsResponse.class, com.movieplatform.proto.notification.GetUserNotificationsResponse.Builder.class);
  }

  private int bitField0_;
  public static final int BASE_RESPONSE_FIELD_NUMBER = 1;
  private com.movieplatform.proto.common.BaseResponse baseResponse_;
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   * @return Whether the baseResponse field is set.
   */
  @java.lang.Override
  public boolean hasBaseResponse() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   * @return The baseResponse.
   */
  @java.lang.Override
  public com.movieplatform.proto.common.BaseResponse getBaseResponse() {
    return baseResponse_ == null ? com.movieplatform.proto.common.BaseResponse.getDefaultInstance() : baseResponse_;
  }
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   */
  @java.lang.Override
  public com.movieplatform.proto.common.BaseResponseOrBuilder getBaseResponseOrBuilder() {
    return baseResponse_ == null ? com.movieplatform.proto.common.BaseResponse.getDefaultInstance() : baseResponse_;
  }

  public static final int NOTIFICATIONS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.movieplatform.proto.notification.UserNotification> notifications_;
  /**
   * <pre>
   * User notifications
   * </pre>
   *
   * <code>repeated .proto.notification.UserNotification notifications = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.movieplatform.proto.notification.UserNotification> getNotificationsList() {
    return notifications_;
  }
  /**
   * <pre>
   * User notifications
   * </pre>
   *
   * <code>repeated .proto.notification.UserNotification notifications = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.movieplatform.proto.notification.UserNotificationOrBuilder> 
      getNotificationsOrBuilderList() {
    return notifications_;
  }
  /**
   * <pre>
   * User notifications
   * </pre>
   *
   * <code>repeated .proto.notification.UserNotification notifications = 2;</code>
   */
  @java.lang.Override
  public int getNotificationsCount() {
    return notifications_.size();
  }
  /**
   * <pre>
   * User notifications
   * </pre>
   *
   * <code>repeated .proto.notification.UserNotification notifications = 2;</code>
   */
  @java.lang.Override
  public com.movieplatform.proto.notification.UserNotification getNotifications(int index) {
    return notifications_.get(index);
  }
  /**
   * <pre>
   * User notifications
   * </pre>
   *
   * <code>repeated .proto.notification.UserNotification notifications = 2;</code>
   */
  @java.lang.Override
  public com.movieplatform.proto.notification.UserNotificationOrBuilder getNotificationsOrBuilder(
      int index) {
    return notifications_.get(index);
  }

  public static final int PAGINATION_FIELD_NUMBER = 3;
  private com.movieplatform.proto.common.PaginationResponse pagination_;
  /**
   * <pre>
   * Pagination information
   * </pre>
   *
   * <code>.proto.common.PaginationResponse pagination = 3;</code>
   * @return Whether the pagination field is set.
   */
  @java.lang.Override
  public boolean hasPagination() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Pagination information
   * </pre>
   *
   * <code>.proto.common.PaginationResponse pagination = 3;</code>
   * @return The pagination.
   */
  @java.lang.Override
  public com.movieplatform.proto.common.PaginationResponse getPagination() {
    return pagination_ == null ? com.movieplatform.proto.common.PaginationResponse.getDefaultInstance() : pagination_;
  }
  /**
   * <pre>
   * Pagination information
   * </pre>
   *
   * <code>.proto.common.PaginationResponse pagination = 3;</code>
   */
  @java.lang.Override
  public com.movieplatform.proto.common.PaginationResponseOrBuilder getPaginationOrBuilder() {
    return pagination_ == null ? com.movieplatform.proto.common.PaginationResponse.getDefaultInstance() : pagination_;
  }

  public static final int TOTAL_COUNT_FIELD_NUMBER = 4;
  private long totalCount_ = 0L;
  /**
   * <pre>
   * Total number of notifications
   * </pre>
   *
   * <code>int64 total_count = 4;</code>
   * @return The totalCount.
   */
  @java.lang.Override
  public long getTotalCount() {
    return totalCount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getBaseResponse());
    }
    for (int i = 0; i < notifications_.size(); i++) {
      output.writeMessage(2, notifications_.get(i));
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getPagination());
    }
    if (totalCount_ != 0L) {
      output.writeInt64(4, totalCount_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBaseResponse());
    }
    for (int i = 0; i < notifications_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, notifications_.get(i));
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getPagination());
    }
    if (totalCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, totalCount_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.movieplatform.proto.notification.GetUserNotificationsResponse)) {
      return super.equals(obj);
    }
    com.movieplatform.proto.notification.GetUserNotificationsResponse other = (com.movieplatform.proto.notification.GetUserNotificationsResponse) obj;

    if (hasBaseResponse() != other.hasBaseResponse()) return false;
    if (hasBaseResponse()) {
      if (!getBaseResponse()
          .equals(other.getBaseResponse())) return false;
    }
    if (!getNotificationsList()
        .equals(other.getNotificationsList())) return false;
    if (hasPagination() != other.hasPagination()) return false;
    if (hasPagination()) {
      if (!getPagination()
          .equals(other.getPagination())) return false;
    }
    if (getTotalCount()
        != other.getTotalCount()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBaseResponse()) {
      hash = (37 * hash) + BASE_RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getBaseResponse().hashCode();
    }
    if (getNotificationsCount() > 0) {
      hash = (37 * hash) + NOTIFICATIONS_FIELD_NUMBER;
      hash = (53 * hash) + getNotificationsList().hashCode();
    }
    if (hasPagination()) {
      hash = (37 * hash) + PAGINATION_FIELD_NUMBER;
      hash = (53 * hash) + getPagination().hashCode();
    }
    hash = (37 * hash) + TOTAL_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalCount());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.movieplatform.proto.notification.GetUserNotificationsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.notification.GetUserNotificationsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.notification.GetUserNotificationsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.notification.GetUserNotificationsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.notification.GetUserNotificationsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.notification.GetUserNotificationsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.notification.GetUserNotificationsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.notification.GetUserNotificationsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.movieplatform.proto.notification.GetUserNotificationsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.movieplatform.proto.notification.GetUserNotificationsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.movieplatform.proto.notification.GetUserNotificationsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.notification.GetUserNotificationsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.movieplatform.proto.notification.GetUserNotificationsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Get user notifications response
   * </pre>
   *
   * Protobuf type {@code proto.notification.GetUserNotificationsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.notification.GetUserNotificationsResponse)
      com.movieplatform.proto.notification.GetUserNotificationsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.movieplatform.proto.notification.NotificationReqResProto.internal_static_proto_notification_GetUserNotificationsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.movieplatform.proto.notification.NotificationReqResProto.internal_static_proto_notification_GetUserNotificationsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.movieplatform.proto.notification.GetUserNotificationsResponse.class, com.movieplatform.proto.notification.GetUserNotificationsResponse.Builder.class);
    }

    // Construct using com.movieplatform.proto.notification.GetUserNotificationsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetBaseResponseFieldBuilder();
        internalGetNotificationsFieldBuilder();
        internalGetPaginationFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      baseResponse_ = null;
      if (baseResponseBuilder_ != null) {
        baseResponseBuilder_.dispose();
        baseResponseBuilder_ = null;
      }
      if (notificationsBuilder_ == null) {
        notifications_ = java.util.Collections.emptyList();
      } else {
        notifications_ = null;
        notificationsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      pagination_ = null;
      if (paginationBuilder_ != null) {
        paginationBuilder_.dispose();
        paginationBuilder_ = null;
      }
      totalCount_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.movieplatform.proto.notification.NotificationReqResProto.internal_static_proto_notification_GetUserNotificationsResponse_descriptor;
    }

    @java.lang.Override
    public com.movieplatform.proto.notification.GetUserNotificationsResponse getDefaultInstanceForType() {
      return com.movieplatform.proto.notification.GetUserNotificationsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.movieplatform.proto.notification.GetUserNotificationsResponse build() {
      com.movieplatform.proto.notification.GetUserNotificationsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.movieplatform.proto.notification.GetUserNotificationsResponse buildPartial() {
      com.movieplatform.proto.notification.GetUserNotificationsResponse result = new com.movieplatform.proto.notification.GetUserNotificationsResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.movieplatform.proto.notification.GetUserNotificationsResponse result) {
      if (notificationsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          notifications_ = java.util.Collections.unmodifiableList(notifications_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.notifications_ = notifications_;
      } else {
        result.notifications_ = notificationsBuilder_.build();
      }
    }

    private void buildPartial0(com.movieplatform.proto.notification.GetUserNotificationsResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.baseResponse_ = baseResponseBuilder_ == null
            ? baseResponse_
            : baseResponseBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.pagination_ = paginationBuilder_ == null
            ? pagination_
            : paginationBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.totalCount_ = totalCount_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.movieplatform.proto.notification.GetUserNotificationsResponse) {
        return mergeFrom((com.movieplatform.proto.notification.GetUserNotificationsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.movieplatform.proto.notification.GetUserNotificationsResponse other) {
      if (other == com.movieplatform.proto.notification.GetUserNotificationsResponse.getDefaultInstance()) return this;
      if (other.hasBaseResponse()) {
        mergeBaseResponse(other.getBaseResponse());
      }
      if (notificationsBuilder_ == null) {
        if (!other.notifications_.isEmpty()) {
          if (notifications_.isEmpty()) {
            notifications_ = other.notifications_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureNotificationsIsMutable();
            notifications_.addAll(other.notifications_);
          }
          onChanged();
        }
      } else {
        if (!other.notifications_.isEmpty()) {
          if (notificationsBuilder_.isEmpty()) {
            notificationsBuilder_.dispose();
            notificationsBuilder_ = null;
            notifications_ = other.notifications_;
            bitField0_ = (bitField0_ & ~0x00000002);
            notificationsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetNotificationsFieldBuilder() : null;
          } else {
            notificationsBuilder_.addAllMessages(other.notifications_);
          }
        }
      }
      if (other.hasPagination()) {
        mergePagination(other.getPagination());
      }
      if (other.getTotalCount() != 0L) {
        setTotalCount(other.getTotalCount());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetBaseResponseFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.movieplatform.proto.notification.UserNotification m =
                  input.readMessage(
                      com.movieplatform.proto.notification.UserNotification.parser(),
                      extensionRegistry);
              if (notificationsBuilder_ == null) {
                ensureNotificationsIsMutable();
                notifications_.add(m);
              } else {
                notificationsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetPaginationFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              totalCount_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.movieplatform.proto.common.BaseResponse baseResponse_;
    private com.google.protobuf.SingleFieldBuilder<
        com.movieplatform.proto.common.BaseResponse, com.movieplatform.proto.common.BaseResponse.Builder, com.movieplatform.proto.common.BaseResponseOrBuilder> baseResponseBuilder_;
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     * @return Whether the baseResponse field is set.
     */
    public boolean hasBaseResponse() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     * @return The baseResponse.
     */
    public com.movieplatform.proto.common.BaseResponse getBaseResponse() {
      if (baseResponseBuilder_ == null) {
        return baseResponse_ == null ? com.movieplatform.proto.common.BaseResponse.getDefaultInstance() : baseResponse_;
      } else {
        return baseResponseBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public Builder setBaseResponse(com.movieplatform.proto.common.BaseResponse value) {
      if (baseResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        baseResponse_ = value;
      } else {
        baseResponseBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public Builder setBaseResponse(
        com.movieplatform.proto.common.BaseResponse.Builder builderForValue) {
      if (baseResponseBuilder_ == null) {
        baseResponse_ = builderForValue.build();
      } else {
        baseResponseBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public Builder mergeBaseResponse(com.movieplatform.proto.common.BaseResponse value) {
      if (baseResponseBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          baseResponse_ != null &&
          baseResponse_ != com.movieplatform.proto.common.BaseResponse.getDefaultInstance()) {
          getBaseResponseBuilder().mergeFrom(value);
        } else {
          baseResponse_ = value;
        }
      } else {
        baseResponseBuilder_.mergeFrom(value);
      }
      if (baseResponse_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public Builder clearBaseResponse() {
      bitField0_ = (bitField0_ & ~0x00000001);
      baseResponse_ = null;
      if (baseResponseBuilder_ != null) {
        baseResponseBuilder_.dispose();
        baseResponseBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public com.movieplatform.proto.common.BaseResponse.Builder getBaseResponseBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetBaseResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public com.movieplatform.proto.common.BaseResponseOrBuilder getBaseResponseOrBuilder() {
      if (baseResponseBuilder_ != null) {
        return baseResponseBuilder_.getMessageOrBuilder();
      } else {
        return baseResponse_ == null ?
            com.movieplatform.proto.common.BaseResponse.getDefaultInstance() : baseResponse_;
      }
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.movieplatform.proto.common.BaseResponse, com.movieplatform.proto.common.BaseResponse.Builder, com.movieplatform.proto.common.BaseResponseOrBuilder> 
        internalGetBaseResponseFieldBuilder() {
      if (baseResponseBuilder_ == null) {
        baseResponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.movieplatform.proto.common.BaseResponse, com.movieplatform.proto.common.BaseResponse.Builder, com.movieplatform.proto.common.BaseResponseOrBuilder>(
                getBaseResponse(),
                getParentForChildren(),
                isClean());
        baseResponse_ = null;
      }
      return baseResponseBuilder_;
    }

    private java.util.List<com.movieplatform.proto.notification.UserNotification> notifications_ =
      java.util.Collections.emptyList();
    private void ensureNotificationsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        notifications_ = new java.util.ArrayList<com.movieplatform.proto.notification.UserNotification>(notifications_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.movieplatform.proto.notification.UserNotification, com.movieplatform.proto.notification.UserNotification.Builder, com.movieplatform.proto.notification.UserNotificationOrBuilder> notificationsBuilder_;

    /**
     * <pre>
     * User notifications
     * </pre>
     *
     * <code>repeated .proto.notification.UserNotification notifications = 2;</code>
     */
    public java.util.List<com.movieplatform.proto.notification.UserNotification> getNotificationsList() {
      if (notificationsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(notifications_);
      } else {
        return notificationsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * User notifications
     * </pre>
     *
     * <code>repeated .proto.notification.UserNotification notifications = 2;</code>
     */
    public int getNotificationsCount() {
      if (notificationsBuilder_ == null) {
        return notifications_.size();
      } else {
        return notificationsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * User notifications
     * </pre>
     *
     * <code>repeated .proto.notification.UserNotification notifications = 2;</code>
     */
    public com.movieplatform.proto.notification.UserNotification getNotifications(int index) {
      if (notificationsBuilder_ == null) {
        return notifications_.get(index);
      } else {
        return notificationsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * User notifications
     * </pre>
     *
     * <code>repeated .proto.notification.UserNotification notifications = 2;</code>
     */
    public Builder setNotifications(
        int index, com.movieplatform.proto.notification.UserNotification value) {
      if (notificationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNotificationsIsMutable();
        notifications_.set(index, value);
        onChanged();
      } else {
        notificationsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * User notifications
     * </pre>
     *
     * <code>repeated .proto.notification.UserNotification notifications = 2;</code>
     */
    public Builder setNotifications(
        int index, com.movieplatform.proto.notification.UserNotification.Builder builderForValue) {
      if (notificationsBuilder_ == null) {
        ensureNotificationsIsMutable();
        notifications_.set(index, builderForValue.build());
        onChanged();
      } else {
        notificationsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * User notifications
     * </pre>
     *
     * <code>repeated .proto.notification.UserNotification notifications = 2;</code>
     */
    public Builder addNotifications(com.movieplatform.proto.notification.UserNotification value) {
      if (notificationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNotificationsIsMutable();
        notifications_.add(value);
        onChanged();
      } else {
        notificationsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * User notifications
     * </pre>
     *
     * <code>repeated .proto.notification.UserNotification notifications = 2;</code>
     */
    public Builder addNotifications(
        int index, com.movieplatform.proto.notification.UserNotification value) {
      if (notificationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNotificationsIsMutable();
        notifications_.add(index, value);
        onChanged();
      } else {
        notificationsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * User notifications
     * </pre>
     *
     * <code>repeated .proto.notification.UserNotification notifications = 2;</code>
     */
    public Builder addNotifications(
        com.movieplatform.proto.notification.UserNotification.Builder builderForValue) {
      if (notificationsBuilder_ == null) {
        ensureNotificationsIsMutable();
        notifications_.add(builderForValue.build());
        onChanged();
      } else {
        notificationsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * User notifications
     * </pre>
     *
     * <code>repeated .proto.notification.UserNotification notifications = 2;</code>
     */
    public Builder addNotifications(
        int index, com.movieplatform.proto.notification.UserNotification.Builder builderForValue) {
      if (notificationsBuilder_ == null) {
        ensureNotificationsIsMutable();
        notifications_.add(index, builderForValue.build());
        onChanged();
      } else {
        notificationsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * User notifications
     * </pre>
     *
     * <code>repeated .proto.notification.UserNotification notifications = 2;</code>
     */
    public Builder addAllNotifications(
        java.lang.Iterable<? extends com.movieplatform.proto.notification.UserNotification> values) {
      if (notificationsBuilder_ == null) {
        ensureNotificationsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, notifications_);
        onChanged();
      } else {
        notificationsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * User notifications
     * </pre>
     *
     * <code>repeated .proto.notification.UserNotification notifications = 2;</code>
     */
    public Builder clearNotifications() {
      if (notificationsBuilder_ == null) {
        notifications_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        notificationsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * User notifications
     * </pre>
     *
     * <code>repeated .proto.notification.UserNotification notifications = 2;</code>
     */
    public Builder removeNotifications(int index) {
      if (notificationsBuilder_ == null) {
        ensureNotificationsIsMutable();
        notifications_.remove(index);
        onChanged();
      } else {
        notificationsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * User notifications
     * </pre>
     *
     * <code>repeated .proto.notification.UserNotification notifications = 2;</code>
     */
    public com.movieplatform.proto.notification.UserNotification.Builder getNotificationsBuilder(
        int index) {
      return internalGetNotificationsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * User notifications
     * </pre>
     *
     * <code>repeated .proto.notification.UserNotification notifications = 2;</code>
     */
    public com.movieplatform.proto.notification.UserNotificationOrBuilder getNotificationsOrBuilder(
        int index) {
      if (notificationsBuilder_ == null) {
        return notifications_.get(index);  } else {
        return notificationsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * User notifications
     * </pre>
     *
     * <code>repeated .proto.notification.UserNotification notifications = 2;</code>
     */
    public java.util.List<? extends com.movieplatform.proto.notification.UserNotificationOrBuilder> 
         getNotificationsOrBuilderList() {
      if (notificationsBuilder_ != null) {
        return notificationsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(notifications_);
      }
    }
    /**
     * <pre>
     * User notifications
     * </pre>
     *
     * <code>repeated .proto.notification.UserNotification notifications = 2;</code>
     */
    public com.movieplatform.proto.notification.UserNotification.Builder addNotificationsBuilder() {
      return internalGetNotificationsFieldBuilder().addBuilder(
          com.movieplatform.proto.notification.UserNotification.getDefaultInstance());
    }
    /**
     * <pre>
     * User notifications
     * </pre>
     *
     * <code>repeated .proto.notification.UserNotification notifications = 2;</code>
     */
    public com.movieplatform.proto.notification.UserNotification.Builder addNotificationsBuilder(
        int index) {
      return internalGetNotificationsFieldBuilder().addBuilder(
          index, com.movieplatform.proto.notification.UserNotification.getDefaultInstance());
    }
    /**
     * <pre>
     * User notifications
     * </pre>
     *
     * <code>repeated .proto.notification.UserNotification notifications = 2;</code>
     */
    public java.util.List<com.movieplatform.proto.notification.UserNotification.Builder> 
         getNotificationsBuilderList() {
      return internalGetNotificationsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.movieplatform.proto.notification.UserNotification, com.movieplatform.proto.notification.UserNotification.Builder, com.movieplatform.proto.notification.UserNotificationOrBuilder> 
        internalGetNotificationsFieldBuilder() {
      if (notificationsBuilder_ == null) {
        notificationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.movieplatform.proto.notification.UserNotification, com.movieplatform.proto.notification.UserNotification.Builder, com.movieplatform.proto.notification.UserNotificationOrBuilder>(
                notifications_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        notifications_ = null;
      }
      return notificationsBuilder_;
    }

    private com.movieplatform.proto.common.PaginationResponse pagination_;
    private com.google.protobuf.SingleFieldBuilder<
        com.movieplatform.proto.common.PaginationResponse, com.movieplatform.proto.common.PaginationResponse.Builder, com.movieplatform.proto.common.PaginationResponseOrBuilder> paginationBuilder_;
    /**
     * <pre>
     * Pagination information
     * </pre>
     *
     * <code>.proto.common.PaginationResponse pagination = 3;</code>
     * @return Whether the pagination field is set.
     */
    public boolean hasPagination() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Pagination information
     * </pre>
     *
     * <code>.proto.common.PaginationResponse pagination = 3;</code>
     * @return The pagination.
     */
    public com.movieplatform.proto.common.PaginationResponse getPagination() {
      if (paginationBuilder_ == null) {
        return pagination_ == null ? com.movieplatform.proto.common.PaginationResponse.getDefaultInstance() : pagination_;
      } else {
        return paginationBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Pagination information
     * </pre>
     *
     * <code>.proto.common.PaginationResponse pagination = 3;</code>
     */
    public Builder setPagination(com.movieplatform.proto.common.PaginationResponse value) {
      if (paginationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pagination_ = value;
      } else {
        paginationBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Pagination information
     * </pre>
     *
     * <code>.proto.common.PaginationResponse pagination = 3;</code>
     */
    public Builder setPagination(
        com.movieplatform.proto.common.PaginationResponse.Builder builderForValue) {
      if (paginationBuilder_ == null) {
        pagination_ = builderForValue.build();
      } else {
        paginationBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Pagination information
     * </pre>
     *
     * <code>.proto.common.PaginationResponse pagination = 3;</code>
     */
    public Builder mergePagination(com.movieplatform.proto.common.PaginationResponse value) {
      if (paginationBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          pagination_ != null &&
          pagination_ != com.movieplatform.proto.common.PaginationResponse.getDefaultInstance()) {
          getPaginationBuilder().mergeFrom(value);
        } else {
          pagination_ = value;
        }
      } else {
        paginationBuilder_.mergeFrom(value);
      }
      if (pagination_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Pagination information
     * </pre>
     *
     * <code>.proto.common.PaginationResponse pagination = 3;</code>
     */
    public Builder clearPagination() {
      bitField0_ = (bitField0_ & ~0x00000004);
      pagination_ = null;
      if (paginationBuilder_ != null) {
        paginationBuilder_.dispose();
        paginationBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Pagination information
     * </pre>
     *
     * <code>.proto.common.PaginationResponse pagination = 3;</code>
     */
    public com.movieplatform.proto.common.PaginationResponse.Builder getPaginationBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetPaginationFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Pagination information
     * </pre>
     *
     * <code>.proto.common.PaginationResponse pagination = 3;</code>
     */
    public com.movieplatform.proto.common.PaginationResponseOrBuilder getPaginationOrBuilder() {
      if (paginationBuilder_ != null) {
        return paginationBuilder_.getMessageOrBuilder();
      } else {
        return pagination_ == null ?
            com.movieplatform.proto.common.PaginationResponse.getDefaultInstance() : pagination_;
      }
    }
    /**
     * <pre>
     * Pagination information
     * </pre>
     *
     * <code>.proto.common.PaginationResponse pagination = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.movieplatform.proto.common.PaginationResponse, com.movieplatform.proto.common.PaginationResponse.Builder, com.movieplatform.proto.common.PaginationResponseOrBuilder> 
        internalGetPaginationFieldBuilder() {
      if (paginationBuilder_ == null) {
        paginationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.movieplatform.proto.common.PaginationResponse, com.movieplatform.proto.common.PaginationResponse.Builder, com.movieplatform.proto.common.PaginationResponseOrBuilder>(
                getPagination(),
                getParentForChildren(),
                isClean());
        pagination_ = null;
      }
      return paginationBuilder_;
    }

    private long totalCount_ ;
    /**
     * <pre>
     * Total number of notifications
     * </pre>
     *
     * <code>int64 total_count = 4;</code>
     * @return The totalCount.
     */
    @java.lang.Override
    public long getTotalCount() {
      return totalCount_;
    }
    /**
     * <pre>
     * Total number of notifications
     * </pre>
     *
     * <code>int64 total_count = 4;</code>
     * @param value The totalCount to set.
     * @return This builder for chaining.
     */
    public Builder setTotalCount(long value) {

      totalCount_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Total number of notifications
     * </pre>
     *
     * <code>int64 total_count = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalCount() {
      bitField0_ = (bitField0_ & ~0x00000008);
      totalCount_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:proto.notification.GetUserNotificationsResponse)
  }

  // @@protoc_insertion_point(class_scope:proto.notification.GetUserNotificationsResponse)
  private static final com.movieplatform.proto.notification.GetUserNotificationsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.movieplatform.proto.notification.GetUserNotificationsResponse();
  }

  public static com.movieplatform.proto.notification.GetUserNotificationsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetUserNotificationsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetUserNotificationsResponse>() {
    @java.lang.Override
    public GetUserNotificationsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetUserNotificationsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetUserNotificationsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.movieplatform.proto.notification.GetUserNotificationsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

