// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notification/notification_req_res.proto
// Protobuf Java Version: 4.29.3

package com.movieplatform.proto.notification;

public interface SendMarketingPushResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.notification.SendMarketingPushResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   * @return Whether the baseResponse field is set.
   */
  boolean hasBaseResponse();
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   * @return The baseResponse.
   */
  com.movieplatform.proto.common.BaseResponse getBaseResponse();
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   */
  com.movieplatform.proto.common.BaseResponseOrBuilder getBaseResponseOrBuilder();

  /**
   * <pre>
   * Campaign push ID
   * </pre>
   *
   * <code>string campaign_push_id = 2;</code>
   * @return The campaignPushId.
   */
  java.lang.String getCampaignPushId();
  /**
   * <pre>
   * Campaign push ID
   * </pre>
   *
   * <code>string campaign_push_id = 2;</code>
   * @return The bytes for campaignPushId.
   */
  com.google.protobuf.ByteString
      getCampaignPushIdBytes();

  /**
   * <pre>
   * Number of pushes scheduled
   * </pre>
   *
   * <code>int32 pushes_scheduled = 3;</code>
   * @return The pushesScheduled.
   */
  int getPushesScheduled();

  /**
   * <pre>
   * When pushes are scheduled
   * </pre>
   *
   * <code>.proto.common.DateTime scheduled_at = 4;</code>
   * @return Whether the scheduledAt field is set.
   */
  boolean hasScheduledAt();
  /**
   * <pre>
   * When pushes are scheduled
   * </pre>
   *
   * <code>.proto.common.DateTime scheduled_at = 4;</code>
   * @return The scheduledAt.
   */
  com.movieplatform.proto.common.DateTime getScheduledAt();
  /**
   * <pre>
   * When pushes are scheduled
   * </pre>
   *
   * <code>.proto.common.DateTime scheduled_at = 4;</code>
   */
  com.movieplatform.proto.common.DateTimeOrBuilder getScheduledAtOrBuilder();
}
