// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: movie/movie_req_res.proto
// Protobuf Java Version: 4.29.3

package com.movieplatform.proto.movie;

/**
 * <pre>
 * Get movies by IDs request
 * </pre>
 *
 * Protobuf type {@code proto.movie.GetMoviesByIDsRequest}
 */
public final class GetMoviesByIDsRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:proto.movie.GetMoviesByIDsRequest)
    GetMoviesByIDsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      GetMoviesByIDsRequest.class.getName());
  }
  // Use GetMoviesByIDsRequest.newBuilder() to construct.
  private GetMoviesByIDsRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetMoviesByIDsRequest() {
    movieIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.movieplatform.proto.movie.MovieReqResProto.internal_static_proto_movie_GetMoviesByIDsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.movieplatform.proto.movie.MovieReqResProto.internal_static_proto_movie_GetMoviesByIDsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.movieplatform.proto.movie.GetMoviesByIDsRequest.class, com.movieplatform.proto.movie.GetMoviesByIDsRequest.Builder.class);
  }

  private int bitField0_;
  public static final int BASE_REQUEST_FIELD_NUMBER = 1;
  private com.movieplatform.proto.common.BaseRequest baseRequest_;
  /**
   * <code>.proto.common.BaseRequest base_request = 1;</code>
   * @return Whether the baseRequest field is set.
   */
  @java.lang.Override
  public boolean hasBaseRequest() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.proto.common.BaseRequest base_request = 1;</code>
   * @return The baseRequest.
   */
  @java.lang.Override
  public com.movieplatform.proto.common.BaseRequest getBaseRequest() {
    return baseRequest_ == null ? com.movieplatform.proto.common.BaseRequest.getDefaultInstance() : baseRequest_;
  }
  /**
   * <code>.proto.common.BaseRequest base_request = 1;</code>
   */
  @java.lang.Override
  public com.movieplatform.proto.common.BaseRequestOrBuilder getBaseRequestOrBuilder() {
    return baseRequest_ == null ? com.movieplatform.proto.common.BaseRequest.getDefaultInstance() : baseRequest_;
  }

  public static final int MOVIE_IDS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList movieIds_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * List of movie IDs
   * </pre>
   *
   * <code>repeated string movie_ids = 2;</code>
   * @return A list containing the movieIds.
   */
  public com.google.protobuf.ProtocolStringList
      getMovieIdsList() {
    return movieIds_;
  }
  /**
   * <pre>
   * List of movie IDs
   * </pre>
   *
   * <code>repeated string movie_ids = 2;</code>
   * @return The count of movieIds.
   */
  public int getMovieIdsCount() {
    return movieIds_.size();
  }
  /**
   * <pre>
   * List of movie IDs
   * </pre>
   *
   * <code>repeated string movie_ids = 2;</code>
   * @param index The index of the element to return.
   * @return The movieIds at the given index.
   */
  public java.lang.String getMovieIds(int index) {
    return movieIds_.get(index);
  }
  /**
   * <pre>
   * List of movie IDs
   * </pre>
   *
   * <code>repeated string movie_ids = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the movieIds at the given index.
   */
  public com.google.protobuf.ByteString
      getMovieIdsBytes(int index) {
    return movieIds_.getByteString(index);
  }

  public static final int INCLUDE_CAST_FIELD_NUMBER = 3;
  private boolean includeCast_ = false;
  /**
   * <pre>
   * Include cast information
   * </pre>
   *
   * <code>bool include_cast = 3;</code>
   * @return The includeCast.
   */
  @java.lang.Override
  public boolean getIncludeCast() {
    return includeCast_;
  }

  public static final int INCLUDE_CREW_FIELD_NUMBER = 4;
  private boolean includeCrew_ = false;
  /**
   * <pre>
   * Include crew information
   * </pre>
   *
   * <code>bool include_crew = 4;</code>
   * @return The includeCrew.
   */
  @java.lang.Override
  public boolean getIncludeCrew() {
    return includeCrew_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getBaseRequest());
    }
    for (int i = 0; i < movieIds_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, movieIds_.getRaw(i));
    }
    if (includeCast_ != false) {
      output.writeBool(3, includeCast_);
    }
    if (includeCrew_ != false) {
      output.writeBool(4, includeCrew_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBaseRequest());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < movieIds_.size(); i++) {
        dataSize += computeStringSizeNoTag(movieIds_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getMovieIdsList().size();
    }
    if (includeCast_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, includeCast_);
    }
    if (includeCrew_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, includeCrew_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.movieplatform.proto.movie.GetMoviesByIDsRequest)) {
      return super.equals(obj);
    }
    com.movieplatform.proto.movie.GetMoviesByIDsRequest other = (com.movieplatform.proto.movie.GetMoviesByIDsRequest) obj;

    if (hasBaseRequest() != other.hasBaseRequest()) return false;
    if (hasBaseRequest()) {
      if (!getBaseRequest()
          .equals(other.getBaseRequest())) return false;
    }
    if (!getMovieIdsList()
        .equals(other.getMovieIdsList())) return false;
    if (getIncludeCast()
        != other.getIncludeCast()) return false;
    if (getIncludeCrew()
        != other.getIncludeCrew()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBaseRequest()) {
      hash = (37 * hash) + BASE_REQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getBaseRequest().hashCode();
    }
    if (getMovieIdsCount() > 0) {
      hash = (37 * hash) + MOVIE_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getMovieIdsList().hashCode();
    }
    hash = (37 * hash) + INCLUDE_CAST_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIncludeCast());
    hash = (37 * hash) + INCLUDE_CREW_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIncludeCrew());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.movieplatform.proto.movie.GetMoviesByIDsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.movie.GetMoviesByIDsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.movie.GetMoviesByIDsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.movie.GetMoviesByIDsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.movie.GetMoviesByIDsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.movie.GetMoviesByIDsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.movie.GetMoviesByIDsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.movie.GetMoviesByIDsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.movieplatform.proto.movie.GetMoviesByIDsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.movieplatform.proto.movie.GetMoviesByIDsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.movieplatform.proto.movie.GetMoviesByIDsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.movie.GetMoviesByIDsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.movieplatform.proto.movie.GetMoviesByIDsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Get movies by IDs request
   * </pre>
   *
   * Protobuf type {@code proto.movie.GetMoviesByIDsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.movie.GetMoviesByIDsRequest)
      com.movieplatform.proto.movie.GetMoviesByIDsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.movieplatform.proto.movie.MovieReqResProto.internal_static_proto_movie_GetMoviesByIDsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.movieplatform.proto.movie.MovieReqResProto.internal_static_proto_movie_GetMoviesByIDsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.movieplatform.proto.movie.GetMoviesByIDsRequest.class, com.movieplatform.proto.movie.GetMoviesByIDsRequest.Builder.class);
    }

    // Construct using com.movieplatform.proto.movie.GetMoviesByIDsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getBaseRequestFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      baseRequest_ = null;
      if (baseRequestBuilder_ != null) {
        baseRequestBuilder_.dispose();
        baseRequestBuilder_ = null;
      }
      movieIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      includeCast_ = false;
      includeCrew_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.movieplatform.proto.movie.MovieReqResProto.internal_static_proto_movie_GetMoviesByIDsRequest_descriptor;
    }

    @java.lang.Override
    public com.movieplatform.proto.movie.GetMoviesByIDsRequest getDefaultInstanceForType() {
      return com.movieplatform.proto.movie.GetMoviesByIDsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.movieplatform.proto.movie.GetMoviesByIDsRequest build() {
      com.movieplatform.proto.movie.GetMoviesByIDsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.movieplatform.proto.movie.GetMoviesByIDsRequest buildPartial() {
      com.movieplatform.proto.movie.GetMoviesByIDsRequest result = new com.movieplatform.proto.movie.GetMoviesByIDsRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.movieplatform.proto.movie.GetMoviesByIDsRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.baseRequest_ = baseRequestBuilder_ == null
            ? baseRequest_
            : baseRequestBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        movieIds_.makeImmutable();
        result.movieIds_ = movieIds_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.includeCast_ = includeCast_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.includeCrew_ = includeCrew_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.movieplatform.proto.movie.GetMoviesByIDsRequest) {
        return mergeFrom((com.movieplatform.proto.movie.GetMoviesByIDsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.movieplatform.proto.movie.GetMoviesByIDsRequest other) {
      if (other == com.movieplatform.proto.movie.GetMoviesByIDsRequest.getDefaultInstance()) return this;
      if (other.hasBaseRequest()) {
        mergeBaseRequest(other.getBaseRequest());
      }
      if (!other.movieIds_.isEmpty()) {
        if (movieIds_.isEmpty()) {
          movieIds_ = other.movieIds_;
          bitField0_ |= 0x00000002;
        } else {
          ensureMovieIdsIsMutable();
          movieIds_.addAll(other.movieIds_);
        }
        onChanged();
      }
      if (other.getIncludeCast() != false) {
        setIncludeCast(other.getIncludeCast());
      }
      if (other.getIncludeCrew() != false) {
        setIncludeCrew(other.getIncludeCrew());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getBaseRequestFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureMovieIdsIsMutable();
              movieIds_.add(s);
              break;
            } // case 18
            case 24: {
              includeCast_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              includeCrew_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.movieplatform.proto.common.BaseRequest baseRequest_;
    private com.google.protobuf.SingleFieldBuilder<
        com.movieplatform.proto.common.BaseRequest, com.movieplatform.proto.common.BaseRequest.Builder, com.movieplatform.proto.common.BaseRequestOrBuilder> baseRequestBuilder_;
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     * @return Whether the baseRequest field is set.
     */
    public boolean hasBaseRequest() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     * @return The baseRequest.
     */
    public com.movieplatform.proto.common.BaseRequest getBaseRequest() {
      if (baseRequestBuilder_ == null) {
        return baseRequest_ == null ? com.movieplatform.proto.common.BaseRequest.getDefaultInstance() : baseRequest_;
      } else {
        return baseRequestBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     */
    public Builder setBaseRequest(com.movieplatform.proto.common.BaseRequest value) {
      if (baseRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        baseRequest_ = value;
      } else {
        baseRequestBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     */
    public Builder setBaseRequest(
        com.movieplatform.proto.common.BaseRequest.Builder builderForValue) {
      if (baseRequestBuilder_ == null) {
        baseRequest_ = builderForValue.build();
      } else {
        baseRequestBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     */
    public Builder mergeBaseRequest(com.movieplatform.proto.common.BaseRequest value) {
      if (baseRequestBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          baseRequest_ != null &&
          baseRequest_ != com.movieplatform.proto.common.BaseRequest.getDefaultInstance()) {
          getBaseRequestBuilder().mergeFrom(value);
        } else {
          baseRequest_ = value;
        }
      } else {
        baseRequestBuilder_.mergeFrom(value);
      }
      if (baseRequest_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     */
    public Builder clearBaseRequest() {
      bitField0_ = (bitField0_ & ~0x00000001);
      baseRequest_ = null;
      if (baseRequestBuilder_ != null) {
        baseRequestBuilder_.dispose();
        baseRequestBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     */
    public com.movieplatform.proto.common.BaseRequest.Builder getBaseRequestBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getBaseRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     */
    public com.movieplatform.proto.common.BaseRequestOrBuilder getBaseRequestOrBuilder() {
      if (baseRequestBuilder_ != null) {
        return baseRequestBuilder_.getMessageOrBuilder();
      } else {
        return baseRequest_ == null ?
            com.movieplatform.proto.common.BaseRequest.getDefaultInstance() : baseRequest_;
      }
    }
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.movieplatform.proto.common.BaseRequest, com.movieplatform.proto.common.BaseRequest.Builder, com.movieplatform.proto.common.BaseRequestOrBuilder> 
        getBaseRequestFieldBuilder() {
      if (baseRequestBuilder_ == null) {
        baseRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.movieplatform.proto.common.BaseRequest, com.movieplatform.proto.common.BaseRequest.Builder, com.movieplatform.proto.common.BaseRequestOrBuilder>(
                getBaseRequest(),
                getParentForChildren(),
                isClean());
        baseRequest_ = null;
      }
      return baseRequestBuilder_;
    }

    private com.google.protobuf.LazyStringArrayList movieIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureMovieIdsIsMutable() {
      if (!movieIds_.isModifiable()) {
        movieIds_ = new com.google.protobuf.LazyStringArrayList(movieIds_);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <pre>
     * List of movie IDs
     * </pre>
     *
     * <code>repeated string movie_ids = 2;</code>
     * @return A list containing the movieIds.
     */
    public com.google.protobuf.ProtocolStringList
        getMovieIdsList() {
      movieIds_.makeImmutable();
      return movieIds_;
    }
    /**
     * <pre>
     * List of movie IDs
     * </pre>
     *
     * <code>repeated string movie_ids = 2;</code>
     * @return The count of movieIds.
     */
    public int getMovieIdsCount() {
      return movieIds_.size();
    }
    /**
     * <pre>
     * List of movie IDs
     * </pre>
     *
     * <code>repeated string movie_ids = 2;</code>
     * @param index The index of the element to return.
     * @return The movieIds at the given index.
     */
    public java.lang.String getMovieIds(int index) {
      return movieIds_.get(index);
    }
    /**
     * <pre>
     * List of movie IDs
     * </pre>
     *
     * <code>repeated string movie_ids = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the movieIds at the given index.
     */
    public com.google.protobuf.ByteString
        getMovieIdsBytes(int index) {
      return movieIds_.getByteString(index);
    }
    /**
     * <pre>
     * List of movie IDs
     * </pre>
     *
     * <code>repeated string movie_ids = 2;</code>
     * @param index The index to set the value at.
     * @param value The movieIds to set.
     * @return This builder for chaining.
     */
    public Builder setMovieIds(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureMovieIdsIsMutable();
      movieIds_.set(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List of movie IDs
     * </pre>
     *
     * <code>repeated string movie_ids = 2;</code>
     * @param value The movieIds to add.
     * @return This builder for chaining.
     */
    public Builder addMovieIds(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureMovieIdsIsMutable();
      movieIds_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List of movie IDs
     * </pre>
     *
     * <code>repeated string movie_ids = 2;</code>
     * @param values The movieIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllMovieIds(
        java.lang.Iterable<java.lang.String> values) {
      ensureMovieIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, movieIds_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List of movie IDs
     * </pre>
     *
     * <code>repeated string movie_ids = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMovieIds() {
      movieIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List of movie IDs
     * </pre>
     *
     * <code>repeated string movie_ids = 2;</code>
     * @param value The bytes of the movieIds to add.
     * @return This builder for chaining.
     */
    public Builder addMovieIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureMovieIdsIsMutable();
      movieIds_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private boolean includeCast_ ;
    /**
     * <pre>
     * Include cast information
     * </pre>
     *
     * <code>bool include_cast = 3;</code>
     * @return The includeCast.
     */
    @java.lang.Override
    public boolean getIncludeCast() {
      return includeCast_;
    }
    /**
     * <pre>
     * Include cast information
     * </pre>
     *
     * <code>bool include_cast = 3;</code>
     * @param value The includeCast to set.
     * @return This builder for chaining.
     */
    public Builder setIncludeCast(boolean value) {

      includeCast_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Include cast information
     * </pre>
     *
     * <code>bool include_cast = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIncludeCast() {
      bitField0_ = (bitField0_ & ~0x00000004);
      includeCast_ = false;
      onChanged();
      return this;
    }

    private boolean includeCrew_ ;
    /**
     * <pre>
     * Include crew information
     * </pre>
     *
     * <code>bool include_crew = 4;</code>
     * @return The includeCrew.
     */
    @java.lang.Override
    public boolean getIncludeCrew() {
      return includeCrew_;
    }
    /**
     * <pre>
     * Include crew information
     * </pre>
     *
     * <code>bool include_crew = 4;</code>
     * @param value The includeCrew to set.
     * @return This builder for chaining.
     */
    public Builder setIncludeCrew(boolean value) {

      includeCrew_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Include crew information
     * </pre>
     *
     * <code>bool include_crew = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIncludeCrew() {
      bitField0_ = (bitField0_ & ~0x00000008);
      includeCrew_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:proto.movie.GetMoviesByIDsRequest)
  }

  // @@protoc_insertion_point(class_scope:proto.movie.GetMoviesByIDsRequest)
  private static final com.movieplatform.proto.movie.GetMoviesByIDsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.movieplatform.proto.movie.GetMoviesByIDsRequest();
  }

  public static com.movieplatform.proto.movie.GetMoviesByIDsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetMoviesByIDsRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetMoviesByIDsRequest>() {
    @java.lang.Override
    public GetMoviesByIDsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetMoviesByIDsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetMoviesByIDsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.movieplatform.proto.movie.GetMoviesByIDsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

