// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: movie/movie_req_res.proto
// Protobuf Java Version: 4.29.3

package com.movieplatform.proto.movie;

/**
 * <pre>
 * Get trending movies request
 * </pre>
 *
 * Protobuf type {@code proto.movie.GetTrendingMoviesRequest}
 */
public final class GetTrendingMoviesRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:proto.movie.GetTrendingMoviesRequest)
    GetTrendingMoviesRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      GetTrendingMoviesRequest.class.getName());
  }
  // Use GetTrendingMoviesRequest.newBuilder() to construct.
  private GetTrendingMoviesRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetTrendingMoviesRequest() {
    timePeriod_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.movieplatform.proto.movie.MovieReqResProto.internal_static_proto_movie_GetTrendingMoviesRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.movieplatform.proto.movie.MovieReqResProto.internal_static_proto_movie_GetTrendingMoviesRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.movieplatform.proto.movie.GetTrendingMoviesRequest.class, com.movieplatform.proto.movie.GetTrendingMoviesRequest.Builder.class);
  }

  private int bitField0_;
  public static final int BASE_REQUEST_FIELD_NUMBER = 1;
  private com.movieplatform.proto.common.BaseRequest baseRequest_;
  /**
   * <code>.proto.common.BaseRequest base_request = 1;</code>
   * @return Whether the baseRequest field is set.
   */
  @java.lang.Override
  public boolean hasBaseRequest() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.proto.common.BaseRequest base_request = 1;</code>
   * @return The baseRequest.
   */
  @java.lang.Override
  public com.movieplatform.proto.common.BaseRequest getBaseRequest() {
    return baseRequest_ == null ? com.movieplatform.proto.common.BaseRequest.getDefaultInstance() : baseRequest_;
  }
  /**
   * <code>.proto.common.BaseRequest base_request = 1;</code>
   */
  @java.lang.Override
  public com.movieplatform.proto.common.BaseRequestOrBuilder getBaseRequestOrBuilder() {
    return baseRequest_ == null ? com.movieplatform.proto.common.BaseRequest.getDefaultInstance() : baseRequest_;
  }

  public static final int LIMIT_FIELD_NUMBER = 2;
  private int limit_ = 0;
  /**
   * <pre>
   * Number of movies to return
   * </pre>
   *
   * <code>int32 limit = 2;</code>
   * @return The limit.
   */
  @java.lang.Override
  public int getLimit() {
    return limit_;
  }

  public static final int TIME_PERIOD_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object timePeriod_ = "";
  /**
   * <pre>
   * Time period (day/week)
   * </pre>
   *
   * <code>string time_period = 3;</code>
   * @return The timePeriod.
   */
  @java.lang.Override
  public java.lang.String getTimePeriod() {
    java.lang.Object ref = timePeriod_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timePeriod_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Time period (day/week)
   * </pre>
   *
   * <code>string time_period = 3;</code>
   * @return The bytes for timePeriod.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTimePeriodBytes() {
    java.lang.Object ref = timePeriod_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timePeriod_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getBaseRequest());
    }
    if (limit_ != 0) {
      output.writeInt32(2, limit_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(timePeriod_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, timePeriod_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBaseRequest());
    }
    if (limit_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, limit_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(timePeriod_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, timePeriod_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.movieplatform.proto.movie.GetTrendingMoviesRequest)) {
      return super.equals(obj);
    }
    com.movieplatform.proto.movie.GetTrendingMoviesRequest other = (com.movieplatform.proto.movie.GetTrendingMoviesRequest) obj;

    if (hasBaseRequest() != other.hasBaseRequest()) return false;
    if (hasBaseRequest()) {
      if (!getBaseRequest()
          .equals(other.getBaseRequest())) return false;
    }
    if (getLimit()
        != other.getLimit()) return false;
    if (!getTimePeriod()
        .equals(other.getTimePeriod())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBaseRequest()) {
      hash = (37 * hash) + BASE_REQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getBaseRequest().hashCode();
    }
    hash = (37 * hash) + LIMIT_FIELD_NUMBER;
    hash = (53 * hash) + getLimit();
    hash = (37 * hash) + TIME_PERIOD_FIELD_NUMBER;
    hash = (53 * hash) + getTimePeriod().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.movieplatform.proto.movie.GetTrendingMoviesRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.movie.GetTrendingMoviesRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.movie.GetTrendingMoviesRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.movie.GetTrendingMoviesRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.movie.GetTrendingMoviesRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.movie.GetTrendingMoviesRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.movie.GetTrendingMoviesRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.movie.GetTrendingMoviesRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.movieplatform.proto.movie.GetTrendingMoviesRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.movieplatform.proto.movie.GetTrendingMoviesRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.movieplatform.proto.movie.GetTrendingMoviesRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.movie.GetTrendingMoviesRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.movieplatform.proto.movie.GetTrendingMoviesRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Get trending movies request
   * </pre>
   *
   * Protobuf type {@code proto.movie.GetTrendingMoviesRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.movie.GetTrendingMoviesRequest)
      com.movieplatform.proto.movie.GetTrendingMoviesRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.movieplatform.proto.movie.MovieReqResProto.internal_static_proto_movie_GetTrendingMoviesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.movieplatform.proto.movie.MovieReqResProto.internal_static_proto_movie_GetTrendingMoviesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.movieplatform.proto.movie.GetTrendingMoviesRequest.class, com.movieplatform.proto.movie.GetTrendingMoviesRequest.Builder.class);
    }

    // Construct using com.movieplatform.proto.movie.GetTrendingMoviesRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getBaseRequestFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      baseRequest_ = null;
      if (baseRequestBuilder_ != null) {
        baseRequestBuilder_.dispose();
        baseRequestBuilder_ = null;
      }
      limit_ = 0;
      timePeriod_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.movieplatform.proto.movie.MovieReqResProto.internal_static_proto_movie_GetTrendingMoviesRequest_descriptor;
    }

    @java.lang.Override
    public com.movieplatform.proto.movie.GetTrendingMoviesRequest getDefaultInstanceForType() {
      return com.movieplatform.proto.movie.GetTrendingMoviesRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.movieplatform.proto.movie.GetTrendingMoviesRequest build() {
      com.movieplatform.proto.movie.GetTrendingMoviesRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.movieplatform.proto.movie.GetTrendingMoviesRequest buildPartial() {
      com.movieplatform.proto.movie.GetTrendingMoviesRequest result = new com.movieplatform.proto.movie.GetTrendingMoviesRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.movieplatform.proto.movie.GetTrendingMoviesRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.baseRequest_ = baseRequestBuilder_ == null
            ? baseRequest_
            : baseRequestBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.limit_ = limit_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.timePeriod_ = timePeriod_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.movieplatform.proto.movie.GetTrendingMoviesRequest) {
        return mergeFrom((com.movieplatform.proto.movie.GetTrendingMoviesRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.movieplatform.proto.movie.GetTrendingMoviesRequest other) {
      if (other == com.movieplatform.proto.movie.GetTrendingMoviesRequest.getDefaultInstance()) return this;
      if (other.hasBaseRequest()) {
        mergeBaseRequest(other.getBaseRequest());
      }
      if (other.getLimit() != 0) {
        setLimit(other.getLimit());
      }
      if (!other.getTimePeriod().isEmpty()) {
        timePeriod_ = other.timePeriod_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getBaseRequestFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              limit_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              timePeriod_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.movieplatform.proto.common.BaseRequest baseRequest_;
    private com.google.protobuf.SingleFieldBuilder<
        com.movieplatform.proto.common.BaseRequest, com.movieplatform.proto.common.BaseRequest.Builder, com.movieplatform.proto.common.BaseRequestOrBuilder> baseRequestBuilder_;
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     * @return Whether the baseRequest field is set.
     */
    public boolean hasBaseRequest() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     * @return The baseRequest.
     */
    public com.movieplatform.proto.common.BaseRequest getBaseRequest() {
      if (baseRequestBuilder_ == null) {
        return baseRequest_ == null ? com.movieplatform.proto.common.BaseRequest.getDefaultInstance() : baseRequest_;
      } else {
        return baseRequestBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     */
    public Builder setBaseRequest(com.movieplatform.proto.common.BaseRequest value) {
      if (baseRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        baseRequest_ = value;
      } else {
        baseRequestBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     */
    public Builder setBaseRequest(
        com.movieplatform.proto.common.BaseRequest.Builder builderForValue) {
      if (baseRequestBuilder_ == null) {
        baseRequest_ = builderForValue.build();
      } else {
        baseRequestBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     */
    public Builder mergeBaseRequest(com.movieplatform.proto.common.BaseRequest value) {
      if (baseRequestBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          baseRequest_ != null &&
          baseRequest_ != com.movieplatform.proto.common.BaseRequest.getDefaultInstance()) {
          getBaseRequestBuilder().mergeFrom(value);
        } else {
          baseRequest_ = value;
        }
      } else {
        baseRequestBuilder_.mergeFrom(value);
      }
      if (baseRequest_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     */
    public Builder clearBaseRequest() {
      bitField0_ = (bitField0_ & ~0x00000001);
      baseRequest_ = null;
      if (baseRequestBuilder_ != null) {
        baseRequestBuilder_.dispose();
        baseRequestBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     */
    public com.movieplatform.proto.common.BaseRequest.Builder getBaseRequestBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getBaseRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     */
    public com.movieplatform.proto.common.BaseRequestOrBuilder getBaseRequestOrBuilder() {
      if (baseRequestBuilder_ != null) {
        return baseRequestBuilder_.getMessageOrBuilder();
      } else {
        return baseRequest_ == null ?
            com.movieplatform.proto.common.BaseRequest.getDefaultInstance() : baseRequest_;
      }
    }
    /**
     * <code>.proto.common.BaseRequest base_request = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.movieplatform.proto.common.BaseRequest, com.movieplatform.proto.common.BaseRequest.Builder, com.movieplatform.proto.common.BaseRequestOrBuilder> 
        getBaseRequestFieldBuilder() {
      if (baseRequestBuilder_ == null) {
        baseRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.movieplatform.proto.common.BaseRequest, com.movieplatform.proto.common.BaseRequest.Builder, com.movieplatform.proto.common.BaseRequestOrBuilder>(
                getBaseRequest(),
                getParentForChildren(),
                isClean());
        baseRequest_ = null;
      }
      return baseRequestBuilder_;
    }

    private int limit_ ;
    /**
     * <pre>
     * Number of movies to return
     * </pre>
     *
     * <code>int32 limit = 2;</code>
     * @return The limit.
     */
    @java.lang.Override
    public int getLimit() {
      return limit_;
    }
    /**
     * <pre>
     * Number of movies to return
     * </pre>
     *
     * <code>int32 limit = 2;</code>
     * @param value The limit to set.
     * @return This builder for chaining.
     */
    public Builder setLimit(int value) {

      limit_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Number of movies to return
     * </pre>
     *
     * <code>int32 limit = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLimit() {
      bitField0_ = (bitField0_ & ~0x00000002);
      limit_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object timePeriod_ = "";
    /**
     * <pre>
     * Time period (day/week)
     * </pre>
     *
     * <code>string time_period = 3;</code>
     * @return The timePeriod.
     */
    public java.lang.String getTimePeriod() {
      java.lang.Object ref = timePeriod_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timePeriod_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Time period (day/week)
     * </pre>
     *
     * <code>string time_period = 3;</code>
     * @return The bytes for timePeriod.
     */
    public com.google.protobuf.ByteString
        getTimePeriodBytes() {
      java.lang.Object ref = timePeriod_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timePeriod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Time period (day/week)
     * </pre>
     *
     * <code>string time_period = 3;</code>
     * @param value The timePeriod to set.
     * @return This builder for chaining.
     */
    public Builder setTimePeriod(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      timePeriod_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Time period (day/week)
     * </pre>
     *
     * <code>string time_period = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimePeriod() {
      timePeriod_ = getDefaultInstance().getTimePeriod();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Time period (day/week)
     * </pre>
     *
     * <code>string time_period = 3;</code>
     * @param value The bytes for timePeriod to set.
     * @return This builder for chaining.
     */
    public Builder setTimePeriodBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      timePeriod_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:proto.movie.GetTrendingMoviesRequest)
  }

  // @@protoc_insertion_point(class_scope:proto.movie.GetTrendingMoviesRequest)
  private static final com.movieplatform.proto.movie.GetTrendingMoviesRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.movieplatform.proto.movie.GetTrendingMoviesRequest();
  }

  public static com.movieplatform.proto.movie.GetTrendingMoviesRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetTrendingMoviesRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetTrendingMoviesRequest>() {
    @java.lang.Override
    public GetTrendingMoviesRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetTrendingMoviesRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetTrendingMoviesRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.movieplatform.proto.movie.GetTrendingMoviesRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

