// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: movie/movie_req_res.proto
// Protobuf Java Version: 4.30.2

package com.movieplatform.proto.movie;

/**
 * <pre>
 * Unpublish movie response
 * </pre>
 *
 * Protobuf type {@code proto.movie.UnpublishMovieResponse}
 */
public final class UnpublishMovieResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:proto.movie.UnpublishMovieResponse)
    UnpublishMovieResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      UnpublishMovieResponse.class.getName());
  }
  // Use UnpublishMovieResponse.newBuilder() to construct.
  private UnpublishMovieResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private UnpublishMovieResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.movieplatform.proto.movie.MovieReqResProto.internal_static_proto_movie_UnpublishMovieResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.movieplatform.proto.movie.MovieReqResProto.internal_static_proto_movie_UnpublishMovieResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.movieplatform.proto.movie.UnpublishMovieResponse.class, com.movieplatform.proto.movie.UnpublishMovieResponse.Builder.class);
  }

  private int bitField0_;
  public static final int BASE_RESPONSE_FIELD_NUMBER = 1;
  private com.movieplatform.proto.common.BaseResponse baseResponse_;
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   * @return Whether the baseResponse field is set.
   */
  @java.lang.Override
  public boolean hasBaseResponse() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   * @return The baseResponse.
   */
  @java.lang.Override
  public com.movieplatform.proto.common.BaseResponse getBaseResponse() {
    return baseResponse_ == null ? com.movieplatform.proto.common.BaseResponse.getDefaultInstance() : baseResponse_;
  }
  /**
   * <code>.proto.common.BaseResponse base_response = 1;</code>
   */
  @java.lang.Override
  public com.movieplatform.proto.common.BaseResponseOrBuilder getBaseResponseOrBuilder() {
    return baseResponse_ == null ? com.movieplatform.proto.common.BaseResponse.getDefaultInstance() : baseResponse_;
  }

  public static final int MOVIE_FIELD_NUMBER = 2;
  private com.movieplatform.proto.movie.Movie movie_;
  /**
   * <pre>
   * Unpublished movie
   * </pre>
   *
   * <code>.proto.movie.Movie movie = 2;</code>
   * @return Whether the movie field is set.
   */
  @java.lang.Override
  public boolean hasMovie() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Unpublished movie
   * </pre>
   *
   * <code>.proto.movie.Movie movie = 2;</code>
   * @return The movie.
   */
  @java.lang.Override
  public com.movieplatform.proto.movie.Movie getMovie() {
    return movie_ == null ? com.movieplatform.proto.movie.Movie.getDefaultInstance() : movie_;
  }
  /**
   * <pre>
   * Unpublished movie
   * </pre>
   *
   * <code>.proto.movie.Movie movie = 2;</code>
   */
  @java.lang.Override
  public com.movieplatform.proto.movie.MovieOrBuilder getMovieOrBuilder() {
    return movie_ == null ? com.movieplatform.proto.movie.Movie.getDefaultInstance() : movie_;
  }

  public static final int UNPUBLISHED_AT_FIELD_NUMBER = 3;
  private com.movieplatform.proto.common.DateTime unpublishedAt_;
  /**
   * <pre>
   * Unpublication timestamp
   * </pre>
   *
   * <code>.proto.common.DateTime unpublished_at = 3;</code>
   * @return Whether the unpublishedAt field is set.
   */
  @java.lang.Override
  public boolean hasUnpublishedAt() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * Unpublication timestamp
   * </pre>
   *
   * <code>.proto.common.DateTime unpublished_at = 3;</code>
   * @return The unpublishedAt.
   */
  @java.lang.Override
  public com.movieplatform.proto.common.DateTime getUnpublishedAt() {
    return unpublishedAt_ == null ? com.movieplatform.proto.common.DateTime.getDefaultInstance() : unpublishedAt_;
  }
  /**
   * <pre>
   * Unpublication timestamp
   * </pre>
   *
   * <code>.proto.common.DateTime unpublished_at = 3;</code>
   */
  @java.lang.Override
  public com.movieplatform.proto.common.DateTimeOrBuilder getUnpublishedAtOrBuilder() {
    return unpublishedAt_ == null ? com.movieplatform.proto.common.DateTime.getDefaultInstance() : unpublishedAt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getBaseResponse());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getMovie());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(3, getUnpublishedAt());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBaseResponse());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getMovie());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getUnpublishedAt());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.movieplatform.proto.movie.UnpublishMovieResponse)) {
      return super.equals(obj);
    }
    com.movieplatform.proto.movie.UnpublishMovieResponse other = (com.movieplatform.proto.movie.UnpublishMovieResponse) obj;

    if (hasBaseResponse() != other.hasBaseResponse()) return false;
    if (hasBaseResponse()) {
      if (!getBaseResponse()
          .equals(other.getBaseResponse())) return false;
    }
    if (hasMovie() != other.hasMovie()) return false;
    if (hasMovie()) {
      if (!getMovie()
          .equals(other.getMovie())) return false;
    }
    if (hasUnpublishedAt() != other.hasUnpublishedAt()) return false;
    if (hasUnpublishedAt()) {
      if (!getUnpublishedAt()
          .equals(other.getUnpublishedAt())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBaseResponse()) {
      hash = (37 * hash) + BASE_RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getBaseResponse().hashCode();
    }
    if (hasMovie()) {
      hash = (37 * hash) + MOVIE_FIELD_NUMBER;
      hash = (53 * hash) + getMovie().hashCode();
    }
    if (hasUnpublishedAt()) {
      hash = (37 * hash) + UNPUBLISHED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getUnpublishedAt().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.movieplatform.proto.movie.UnpublishMovieResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.movie.UnpublishMovieResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.movie.UnpublishMovieResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.movie.UnpublishMovieResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.movie.UnpublishMovieResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.movieplatform.proto.movie.UnpublishMovieResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.movieplatform.proto.movie.UnpublishMovieResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.movie.UnpublishMovieResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.movieplatform.proto.movie.UnpublishMovieResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.movieplatform.proto.movie.UnpublishMovieResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.movieplatform.proto.movie.UnpublishMovieResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.movieplatform.proto.movie.UnpublishMovieResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.movieplatform.proto.movie.UnpublishMovieResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Unpublish movie response
   * </pre>
   *
   * Protobuf type {@code proto.movie.UnpublishMovieResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.movie.UnpublishMovieResponse)
      com.movieplatform.proto.movie.UnpublishMovieResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.movieplatform.proto.movie.MovieReqResProto.internal_static_proto_movie_UnpublishMovieResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.movieplatform.proto.movie.MovieReqResProto.internal_static_proto_movie_UnpublishMovieResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.movieplatform.proto.movie.UnpublishMovieResponse.class, com.movieplatform.proto.movie.UnpublishMovieResponse.Builder.class);
    }

    // Construct using com.movieplatform.proto.movie.UnpublishMovieResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetBaseResponseFieldBuilder();
        internalGetMovieFieldBuilder();
        internalGetUnpublishedAtFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      baseResponse_ = null;
      if (baseResponseBuilder_ != null) {
        baseResponseBuilder_.dispose();
        baseResponseBuilder_ = null;
      }
      movie_ = null;
      if (movieBuilder_ != null) {
        movieBuilder_.dispose();
        movieBuilder_ = null;
      }
      unpublishedAt_ = null;
      if (unpublishedAtBuilder_ != null) {
        unpublishedAtBuilder_.dispose();
        unpublishedAtBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.movieplatform.proto.movie.MovieReqResProto.internal_static_proto_movie_UnpublishMovieResponse_descriptor;
    }

    @java.lang.Override
    public com.movieplatform.proto.movie.UnpublishMovieResponse getDefaultInstanceForType() {
      return com.movieplatform.proto.movie.UnpublishMovieResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.movieplatform.proto.movie.UnpublishMovieResponse build() {
      com.movieplatform.proto.movie.UnpublishMovieResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.movieplatform.proto.movie.UnpublishMovieResponse buildPartial() {
      com.movieplatform.proto.movie.UnpublishMovieResponse result = new com.movieplatform.proto.movie.UnpublishMovieResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.movieplatform.proto.movie.UnpublishMovieResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.baseResponse_ = baseResponseBuilder_ == null
            ? baseResponse_
            : baseResponseBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.movie_ = movieBuilder_ == null
            ? movie_
            : movieBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.unpublishedAt_ = unpublishedAtBuilder_ == null
            ? unpublishedAt_
            : unpublishedAtBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.movieplatform.proto.movie.UnpublishMovieResponse) {
        return mergeFrom((com.movieplatform.proto.movie.UnpublishMovieResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.movieplatform.proto.movie.UnpublishMovieResponse other) {
      if (other == com.movieplatform.proto.movie.UnpublishMovieResponse.getDefaultInstance()) return this;
      if (other.hasBaseResponse()) {
        mergeBaseResponse(other.getBaseResponse());
      }
      if (other.hasMovie()) {
        mergeMovie(other.getMovie());
      }
      if (other.hasUnpublishedAt()) {
        mergeUnpublishedAt(other.getUnpublishedAt());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetBaseResponseFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetMovieFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetUnpublishedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.movieplatform.proto.common.BaseResponse baseResponse_;
    private com.google.protobuf.SingleFieldBuilder<
        com.movieplatform.proto.common.BaseResponse, com.movieplatform.proto.common.BaseResponse.Builder, com.movieplatform.proto.common.BaseResponseOrBuilder> baseResponseBuilder_;
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     * @return Whether the baseResponse field is set.
     */
    public boolean hasBaseResponse() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     * @return The baseResponse.
     */
    public com.movieplatform.proto.common.BaseResponse getBaseResponse() {
      if (baseResponseBuilder_ == null) {
        return baseResponse_ == null ? com.movieplatform.proto.common.BaseResponse.getDefaultInstance() : baseResponse_;
      } else {
        return baseResponseBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public Builder setBaseResponse(com.movieplatform.proto.common.BaseResponse value) {
      if (baseResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        baseResponse_ = value;
      } else {
        baseResponseBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public Builder setBaseResponse(
        com.movieplatform.proto.common.BaseResponse.Builder builderForValue) {
      if (baseResponseBuilder_ == null) {
        baseResponse_ = builderForValue.build();
      } else {
        baseResponseBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public Builder mergeBaseResponse(com.movieplatform.proto.common.BaseResponse value) {
      if (baseResponseBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          baseResponse_ != null &&
          baseResponse_ != com.movieplatform.proto.common.BaseResponse.getDefaultInstance()) {
          getBaseResponseBuilder().mergeFrom(value);
        } else {
          baseResponse_ = value;
        }
      } else {
        baseResponseBuilder_.mergeFrom(value);
      }
      if (baseResponse_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public Builder clearBaseResponse() {
      bitField0_ = (bitField0_ & ~0x00000001);
      baseResponse_ = null;
      if (baseResponseBuilder_ != null) {
        baseResponseBuilder_.dispose();
        baseResponseBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public com.movieplatform.proto.common.BaseResponse.Builder getBaseResponseBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetBaseResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    public com.movieplatform.proto.common.BaseResponseOrBuilder getBaseResponseOrBuilder() {
      if (baseResponseBuilder_ != null) {
        return baseResponseBuilder_.getMessageOrBuilder();
      } else {
        return baseResponse_ == null ?
            com.movieplatform.proto.common.BaseResponse.getDefaultInstance() : baseResponse_;
      }
    }
    /**
     * <code>.proto.common.BaseResponse base_response = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.movieplatform.proto.common.BaseResponse, com.movieplatform.proto.common.BaseResponse.Builder, com.movieplatform.proto.common.BaseResponseOrBuilder> 
        internalGetBaseResponseFieldBuilder() {
      if (baseResponseBuilder_ == null) {
        baseResponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.movieplatform.proto.common.BaseResponse, com.movieplatform.proto.common.BaseResponse.Builder, com.movieplatform.proto.common.BaseResponseOrBuilder>(
                getBaseResponse(),
                getParentForChildren(),
                isClean());
        baseResponse_ = null;
      }
      return baseResponseBuilder_;
    }

    private com.movieplatform.proto.movie.Movie movie_;
    private com.google.protobuf.SingleFieldBuilder<
        com.movieplatform.proto.movie.Movie, com.movieplatform.proto.movie.Movie.Builder, com.movieplatform.proto.movie.MovieOrBuilder> movieBuilder_;
    /**
     * <pre>
     * Unpublished movie
     * </pre>
     *
     * <code>.proto.movie.Movie movie = 2;</code>
     * @return Whether the movie field is set.
     */
    public boolean hasMovie() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Unpublished movie
     * </pre>
     *
     * <code>.proto.movie.Movie movie = 2;</code>
     * @return The movie.
     */
    public com.movieplatform.proto.movie.Movie getMovie() {
      if (movieBuilder_ == null) {
        return movie_ == null ? com.movieplatform.proto.movie.Movie.getDefaultInstance() : movie_;
      } else {
        return movieBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Unpublished movie
     * </pre>
     *
     * <code>.proto.movie.Movie movie = 2;</code>
     */
    public Builder setMovie(com.movieplatform.proto.movie.Movie value) {
      if (movieBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        movie_ = value;
      } else {
        movieBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unpublished movie
     * </pre>
     *
     * <code>.proto.movie.Movie movie = 2;</code>
     */
    public Builder setMovie(
        com.movieplatform.proto.movie.Movie.Builder builderForValue) {
      if (movieBuilder_ == null) {
        movie_ = builderForValue.build();
      } else {
        movieBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unpublished movie
     * </pre>
     *
     * <code>.proto.movie.Movie movie = 2;</code>
     */
    public Builder mergeMovie(com.movieplatform.proto.movie.Movie value) {
      if (movieBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          movie_ != null &&
          movie_ != com.movieplatform.proto.movie.Movie.getDefaultInstance()) {
          getMovieBuilder().mergeFrom(value);
        } else {
          movie_ = value;
        }
      } else {
        movieBuilder_.mergeFrom(value);
      }
      if (movie_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Unpublished movie
     * </pre>
     *
     * <code>.proto.movie.Movie movie = 2;</code>
     */
    public Builder clearMovie() {
      bitField0_ = (bitField0_ & ~0x00000002);
      movie_ = null;
      if (movieBuilder_ != null) {
        movieBuilder_.dispose();
        movieBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unpublished movie
     * </pre>
     *
     * <code>.proto.movie.Movie movie = 2;</code>
     */
    public com.movieplatform.proto.movie.Movie.Builder getMovieBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetMovieFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Unpublished movie
     * </pre>
     *
     * <code>.proto.movie.Movie movie = 2;</code>
     */
    public com.movieplatform.proto.movie.MovieOrBuilder getMovieOrBuilder() {
      if (movieBuilder_ != null) {
        return movieBuilder_.getMessageOrBuilder();
      } else {
        return movie_ == null ?
            com.movieplatform.proto.movie.Movie.getDefaultInstance() : movie_;
      }
    }
    /**
     * <pre>
     * Unpublished movie
     * </pre>
     *
     * <code>.proto.movie.Movie movie = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.movieplatform.proto.movie.Movie, com.movieplatform.proto.movie.Movie.Builder, com.movieplatform.proto.movie.MovieOrBuilder> 
        internalGetMovieFieldBuilder() {
      if (movieBuilder_ == null) {
        movieBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.movieplatform.proto.movie.Movie, com.movieplatform.proto.movie.Movie.Builder, com.movieplatform.proto.movie.MovieOrBuilder>(
                getMovie(),
                getParentForChildren(),
                isClean());
        movie_ = null;
      }
      return movieBuilder_;
    }

    private com.movieplatform.proto.common.DateTime unpublishedAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.movieplatform.proto.common.DateTime, com.movieplatform.proto.common.DateTime.Builder, com.movieplatform.proto.common.DateTimeOrBuilder> unpublishedAtBuilder_;
    /**
     * <pre>
     * Unpublication timestamp
     * </pre>
     *
     * <code>.proto.common.DateTime unpublished_at = 3;</code>
     * @return Whether the unpublishedAt field is set.
     */
    public boolean hasUnpublishedAt() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Unpublication timestamp
     * </pre>
     *
     * <code>.proto.common.DateTime unpublished_at = 3;</code>
     * @return The unpublishedAt.
     */
    public com.movieplatform.proto.common.DateTime getUnpublishedAt() {
      if (unpublishedAtBuilder_ == null) {
        return unpublishedAt_ == null ? com.movieplatform.proto.common.DateTime.getDefaultInstance() : unpublishedAt_;
      } else {
        return unpublishedAtBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Unpublication timestamp
     * </pre>
     *
     * <code>.proto.common.DateTime unpublished_at = 3;</code>
     */
    public Builder setUnpublishedAt(com.movieplatform.proto.common.DateTime value) {
      if (unpublishedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        unpublishedAt_ = value;
      } else {
        unpublishedAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unpublication timestamp
     * </pre>
     *
     * <code>.proto.common.DateTime unpublished_at = 3;</code>
     */
    public Builder setUnpublishedAt(
        com.movieplatform.proto.common.DateTime.Builder builderForValue) {
      if (unpublishedAtBuilder_ == null) {
        unpublishedAt_ = builderForValue.build();
      } else {
        unpublishedAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unpublication timestamp
     * </pre>
     *
     * <code>.proto.common.DateTime unpublished_at = 3;</code>
     */
    public Builder mergeUnpublishedAt(com.movieplatform.proto.common.DateTime value) {
      if (unpublishedAtBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          unpublishedAt_ != null &&
          unpublishedAt_ != com.movieplatform.proto.common.DateTime.getDefaultInstance()) {
          getUnpublishedAtBuilder().mergeFrom(value);
        } else {
          unpublishedAt_ = value;
        }
      } else {
        unpublishedAtBuilder_.mergeFrom(value);
      }
      if (unpublishedAt_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Unpublication timestamp
     * </pre>
     *
     * <code>.proto.common.DateTime unpublished_at = 3;</code>
     */
    public Builder clearUnpublishedAt() {
      bitField0_ = (bitField0_ & ~0x00000004);
      unpublishedAt_ = null;
      if (unpublishedAtBuilder_ != null) {
        unpublishedAtBuilder_.dispose();
        unpublishedAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unpublication timestamp
     * </pre>
     *
     * <code>.proto.common.DateTime unpublished_at = 3;</code>
     */
    public com.movieplatform.proto.common.DateTime.Builder getUnpublishedAtBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetUnpublishedAtFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Unpublication timestamp
     * </pre>
     *
     * <code>.proto.common.DateTime unpublished_at = 3;</code>
     */
    public com.movieplatform.proto.common.DateTimeOrBuilder getUnpublishedAtOrBuilder() {
      if (unpublishedAtBuilder_ != null) {
        return unpublishedAtBuilder_.getMessageOrBuilder();
      } else {
        return unpublishedAt_ == null ?
            com.movieplatform.proto.common.DateTime.getDefaultInstance() : unpublishedAt_;
      }
    }
    /**
     * <pre>
     * Unpublication timestamp
     * </pre>
     *
     * <code>.proto.common.DateTime unpublished_at = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.movieplatform.proto.common.DateTime, com.movieplatform.proto.common.DateTime.Builder, com.movieplatform.proto.common.DateTimeOrBuilder> 
        internalGetUnpublishedAtFieldBuilder() {
      if (unpublishedAtBuilder_ == null) {
        unpublishedAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.movieplatform.proto.common.DateTime, com.movieplatform.proto.common.DateTime.Builder, com.movieplatform.proto.common.DateTimeOrBuilder>(
                getUnpublishedAt(),
                getParentForChildren(),
                isClean());
        unpublishedAt_ = null;
      }
      return unpublishedAtBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:proto.movie.UnpublishMovieResponse)
  }

  // @@protoc_insertion_point(class_scope:proto.movie.UnpublishMovieResponse)
  private static final com.movieplatform.proto.movie.UnpublishMovieResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.movieplatform.proto.movie.UnpublishMovieResponse();
  }

  public static com.movieplatform.proto.movie.UnpublishMovieResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UnpublishMovieResponse>
      PARSER = new com.google.protobuf.AbstractParser<UnpublishMovieResponse>() {
    @java.lang.Override
    public UnpublishMovieResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UnpublishMovieResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UnpublishMovieResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.movieplatform.proto.movie.UnpublishMovieResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

